/* Generated by Snowball 2.0.0 - https://snowballstem.org/ */


#include <xapian-internal.h>
#pragma hdrstop
#include "dutch.sbl.h"

static const symbol s_pool[] = {
#define s_0_1 0
0xC3, 0xA1,
#define s_0_2 2
0xC3, 0xA4,
#define s_0_3 4
0xC3, 0xA9,
#define s_0_4 6
0xC3, 0xAB,
#define s_0_5 8
0xC3, 0xAD,
#define s_0_6 10
0xC3, 0xAF,
#define s_0_7 12
0xC3, 0xB3,
#define s_0_8 14
0xC3, 0xB6,
#define s_0_9 16
0xC3, 0xBA,
#define s_0_10 18
0xC3, 0xBC,
#define s_1_1 20
'I',
#define s_1_2 21
'Y',
#define s_2_0 22
'd', 'd',
#define s_2_1 24
'k', 'k',
#define s_2_2 26
't', 't',
#define s_3_0 28
'e', 'n', 'e',
#define s_3_1 31
's', 'e',
#define s_3_2 s_3_0
#define s_3_3 33
'h', 'e', 'd', 'e', 'n',
#define s_3_4 s_3_1
#define s_4_0 38
'e', 'n', 'd',
#define s_4_1 41
'i', 'g',
#define s_4_2 43
'i', 'n', 'g',
#define s_4_3 46
'l', 'i', 'j', 'k',
#define s_4_4 50
'b', 'a', 'a', 'r',
#define s_4_5 54
'b', 'a', 'r',
#define s_5_0 57
'a', 'a',
#define s_5_1 59
'e', 'e',
#define s_5_2 61
'o', 'o',
#define s_5_3 63
'u', 'u',
};


static const Among a_0[11] = {
/*  0 */ { 0, 0, -1, 6},
/*  1 */ { 2, s_0_1, 0, 1},
/*  2 */ { 2, s_0_2, 0, 1},
/*  3 */ { 2, s_0_3, 0, 2},
/*  4 */ { 2, s_0_4, 0, 2},
/*  5 */ { 2, s_0_5, 0, 3},
/*  6 */ { 2, s_0_6, 0, 3},
/*  7 */ { 2, s_0_7, 0, 4},
/*  8 */ { 2, s_0_8, 0, 4},
/*  9 */ { 2, s_0_9, 0, 5},
/* 10 */ { 2, s_0_10, 0, 5}
};


static const Among a_1[3] = {
/*  0 */ { 0, 0, -1, 3},
/*  1 */ { 1, s_1_1, 0, 2},
/*  2 */ { 1, s_1_2, 0, 1}
};


static const Among a_2[3] = {
/*  0 */ { 2, s_2_0, -1, -1},
/*  1 */ { 2, s_2_1, -1, -1},
/*  2 */ { 2, s_2_2, -1, -1}
};


static const Among a_3[5] = {
/*  0 */ { 3, s_3_0, -1, 2},
/*  1 */ { 2, s_3_1, -1, 3},
/*  2 */ { 2, s_3_2, -1, 2},
/*  3 */ { 5, s_3_3, 2, 1},
/*  4 */ { 1, s_3_4, -1, 3}
};


static const Among a_4[6] = {
/*  0 */ { 3, s_4_0, -1, 1},
/*  1 */ { 2, s_4_1, -1, 2},
/*  2 */ { 3, s_4_2, -1, 1},
/*  3 */ { 4, s_4_3, -1, 3},
/*  4 */ { 4, s_4_4, -1, 4},
/*  5 */ { 3, s_4_5, -1, 5}
};


static const Among a_5[4] = {
/*  0 */ { 2, s_5_0, -1, -1},
/*  1 */ { 2, s_5_1, -1, -1},
/*  2 */ { 2, s_5_2, -1, -1},
/*  3 */ { 2, s_5_3, -1, -1}
};

static const uchar g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 };

static const uchar g_v_I[] = { 1, 0, 0, 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 };

static const uchar g_v_j[] = { 17, 67, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128 };

static const symbol s_0[] = { 'a' };
static const symbol s_1[] = { 'e' };
static const symbol s_2[] = { 'i' };
static const symbol s_3[] = { 'o' };
static const symbol s_4[] = { 'u' };
static const symbol s_5[] = { 'Y' };
static const symbol s_6[] = { 'I' };
static const symbol s_7[] = { 'Y' };
static const symbol s_8[] = { 'y' };
static const symbol s_9[] = { 'i' };
static const symbol s_10[] = { 'g', 'e', 'm' };
static const symbol s_11[] = { 'h', 'e', 'i', 'd' };
static const symbol s_12[] = { 'h', 'e', 'i', 'd' };
static const symbol s_13[] = { 'e', 'n' };
static const symbol s_14[] = { 'i', 'g' };

int Xapian::InternalStemDutch::r_prelude() {
	int among_var;
	{   int c_test1 = c;
		while(1) {
			int c2 = c;
			bra = c;
			if(c + 1 >= l || p[c + 1] >> 5 != 5 || !((340306450 >> (p[c + 1] & 0x1f)) & 1)) among_var = 6; else
			among_var = find_among(s_pool, a_0, 11, 0, 0);
			if(!(among_var)) goto lab0;
			ket = c;
			switch(among_var) {
				case 1:
					{    int ret = slice_from_s(1, s_0);
						if(ret < 0) return ret;
					}
					break;
				case 2:
					{    int ret = slice_from_s(1, s_1);
						if(ret < 0) return ret;
					}
					break;
				case 3:
					{    int ret = slice_from_s(1, s_2);
						if(ret < 0) return ret;
					}
					break;
				case 4:
					{    int ret = slice_from_s(1, s_3);
						if(ret < 0) return ret;
					}
					break;
				case 5:
					{    int ret = slice_from_s(1, s_4);
						if(ret < 0) return ret;
					}
					break;
				case 6:
					{    int ret = skip_utf8(p, c, 0, l, 1);
						if(ret < 0) goto lab0;
						c = ret;
					}
					break;
			}
			continue;
		lab0:
			c = c2;
			break;
		}
		c = c_test1;
	}
	{   int c3 = c;
		bra = c;
		if(c == l || p[c] != 'y') { c = c3; goto lab1; }
		c++;
		ket = c;
		{    int ret = slice_from_s(1, s_5);
			if(ret < 0) return ret;
		}
	lab1:
		;
	}
	while(1) {
		int c4 = c;
		while(1) {
			int c5 = c;
			if(in_grouping_U(g_v, 97, 232, 0)) goto lab3;
			bra = c;
			{   int c6 = c;
				if(c == l || p[c] != 'i') goto lab5;
				c++;
				ket = c;
				if(in_grouping_U(g_v, 97, 232, 0)) goto lab5;
				{    int ret = slice_from_s(1, s_6);
					if(ret < 0) return ret;
				}
				goto lab4;
			lab5:
				c = c6;
				if(c == l || p[c] != 'y') goto lab3;
				c++;
				ket = c;
				{    int ret = slice_from_s(1, s_7);
					if(ret < 0) return ret;
				}
			}
		lab4:
			c = c5;
			break;
		lab3:
			c = c5;
			{    int ret = skip_utf8(p, c, 0, l, 1);
				if(ret < 0) goto lab2;
				c = ret;
			}
		}
		continue;
	lab2:
		c = c4;
		break;
	}
	return 1;
}

int Xapian::InternalStemDutch::r_mark_regions() {
	I_p1 = l;
	I_p2 = l;
	{   
		int ret = out_grouping_U(g_v, 97, 232, 1);
		if(ret < 0) return 0;
		c += ret;
	}
	{   
		int ret = in_grouping_U(g_v, 97, 232, 1);
		if(ret < 0) return 0;
		c += ret;
	}
	I_p1 = c;
	
	if(!(I_p1 < 3)) goto lab0;
	I_p1 = 3;
lab0:
	{   
		int ret = out_grouping_U(g_v, 97, 232, 1);
		if(ret < 0) return 0;
		c += ret;
	}
	{   
		int ret = in_grouping_U(g_v, 97, 232, 1);
		if(ret < 0) return 0;
		c += ret;
	}
	I_p2 = c;
	return 1;
}

int Xapian::InternalStemDutch::r_postlude() {
	int among_var;
	while(1) {
		int c1 = c;
		bra = c;
		if(c >= l || (p[c + 0] != 73 && p[c + 0] != 89)) among_var = 3; else
		among_var = find_among(s_pool, a_1, 3, 0, 0);
		if(!(among_var)) goto lab0;
		ket = c;
		switch(among_var) {
			case 1:
				{    int ret = slice_from_s(1, s_8);
					if(ret < 0) return ret;
				}
				break;
			case 2:
				{    int ret = slice_from_s(1, s_9);
					if(ret < 0) return ret;
				}
				break;
			case 3:
				{    int ret = skip_utf8(p, c, 0, l, 1);
					if(ret < 0) goto lab0;
					c = ret;
				}
				break;
		}
		continue;
	lab0:
		c = c1;
		break;
	}
	return 1;
}

int Xapian::InternalStemDutch::r_R1() {
	if(!(I_p1 <= c)) return 0;
	return 1;
}

int Xapian::InternalStemDutch::r_R2() {
	if(!(I_p2 <= c)) return 0;
	return 1;
}

int Xapian::InternalStemDutch::r_undouble() {
	{   int m_test1 = l - c;
		if(c - 1 <= lb || p[c-1] >> 5 != 3 || !((1050640 >> (p[c-1] & 0x1f)) & 1)) return 0;
		if(!(find_among_b(s_pool, a_2, 3, 0, 0))) return 0;
		c = l - m_test1;
	}
	ket = c;
	{    int ret = skip_utf8(p, c, lb, 0, -1);
		if(ret < 0) return 0;
		c = ret;
	}
	bra = c;
	{    int ret = slice_del();
		if(ret < 0) return ret;
	}
	return 1;
}

int Xapian::InternalStemDutch::r_e_ending() {
	I_e_found = 0;
	ket = c;
	if(c <= lb || p[c - 1] != 'e') return 0;
	c--;
	bra = c;
	{    int ret = r_R1();
		if(ret <= 0) return ret;
	}
	{   int m_test1 = l - c;
		if(out_grouping_b_U(g_v, 97, 232, 0)) return 0;
		c = l - m_test1;
	}
	{    int ret = slice_del();
		if(ret < 0) return ret;
	}
	I_e_found = 1;
	{    int ret = r_undouble();
		if(ret <= 0) return ret;
	}
	return 1;
}

int Xapian::InternalStemDutch::r_en_ending() {
	{    int ret = r_R1();
		if(ret <= 0) return ret;
	}
	{   int m1 = l - c; (void)m1;
		if(out_grouping_b_U(g_v, 97, 232, 0)) return 0;
		c = l - m1;
		{   int m2 = l - c; (void)m2;
			if(!(eq_s_b(3, s_10))) goto lab0;
			return 0;
		lab0:
			c = l - m2;
		}
	}
	{    int ret = slice_del();
		if(ret < 0) return ret;
	}
	{    int ret = r_undouble();
		if(ret <= 0) return ret;
	}
	return 1;
}

int Xapian::InternalStemDutch::r_standard_suffix() {
	int among_var;
	{   int m1 = l - c; (void)m1;
		ket = c;
		if(c <= lb || p[c-1] >> 5 != 3 || !((540704 >> (p[c-1] & 0x1f)) & 1)) goto lab0;
		among_var = find_among_b(s_pool, a_3, 5, 0, 0);
		if(!(among_var)) goto lab0;
		bra = c;
		switch(among_var) {
			case 1:
				{    int ret = r_R1();
					if(ret == 0) goto lab0;
					if(ret < 0) return ret;
				}
				{    int ret = slice_from_s(4, s_11);
					if(ret < 0) return ret;
				}
				break;
			case 2:
				{    int ret = r_en_ending();
					if(ret == 0) goto lab0;
					if(ret < 0) return ret;
				}
				break;
			case 3:
				{    int ret = r_R1();
					if(ret == 0) goto lab0;
					if(ret < 0) return ret;
				}
				if(out_grouping_b_U(g_v_j, 97, 232, 0)) goto lab0;
				{    int ret = slice_del();
					if(ret < 0) return ret;
				}
				break;
		}
	lab0:
		c = l - m1;
	}
	{   int m2 = l - c; (void)m2;
		{   int ret = r_e_ending();
			if(ret < 0) return ret;
		}
		c = l - m2;
	}
	{   int m3 = l - c; (void)m3;
		ket = c;
		if(!(eq_s_b(4, s_12))) goto lab1;
		bra = c;
		{    int ret = r_R2();
			if(ret == 0) goto lab1;
			if(ret < 0) return ret;
		}
		{   int m4 = l - c; (void)m4;
			if(c <= lb || p[c - 1] != 'c') goto lab2;
			c--;
			goto lab1;
		lab2:
			c = l - m4;
		}
		{    int ret = slice_del();
			if(ret < 0) return ret;
		}
		ket = c;
		if(!(eq_s_b(2, s_13))) goto lab1;
		bra = c;
		{    int ret = r_en_ending();
			if(ret == 0) goto lab1;
			if(ret < 0) return ret;
		}
	lab1:
		c = l - m3;
	}
	{   int m5 = l - c; (void)m5;
		ket = c;
		if(c - 1 <= lb || p[c-1] >> 5 != 3 || !((264336 >> (p[c-1] & 0x1f)) & 1)) goto lab3;
		among_var = find_among_b(s_pool, a_4, 6, 0, 0);
		if(!(among_var)) goto lab3;
		bra = c;
		switch(among_var) {
			case 1:
				{    int ret = r_R2();
					if(ret == 0) goto lab3;
					if(ret < 0) return ret;
				}
				{    int ret = slice_del();
					if(ret < 0) return ret;
				}
				{   int m6 = l - c; (void)m6;
					ket = c;
					if(!(eq_s_b(2, s_14))) goto lab5;
					bra = c;
					{    int ret = r_R2();
						if(ret == 0) goto lab5;
						if(ret < 0) return ret;
					}
					{   int m7 = l - c; (void)m7;
						if(c <= lb || p[c - 1] != 'e') goto lab6;
						c--;
						goto lab5;
					lab6:
						c = l - m7;
					}
					{    int ret = slice_del();
						if(ret < 0) return ret;
					}
					goto lab4;
				lab5:
					c = l - m6;
					{    int ret = r_undouble();
						if(ret == 0) goto lab3;
						if(ret < 0) return ret;
					}
				}
			lab4:
				break;
			case 2:
				{    int ret = r_R2();
					if(ret == 0) goto lab3;
					if(ret < 0) return ret;
				}
				{   int m8 = l - c; (void)m8;
					if(c <= lb || p[c - 1] != 'e') goto lab7;
					c--;
					goto lab3;
				lab7:
					c = l - m8;
				}
				{    int ret = slice_del();
					if(ret < 0) return ret;
				}
				break;
			case 3:
				{    int ret = r_R2();
					if(ret == 0) goto lab3;
					if(ret < 0) return ret;
				}
				{    int ret = slice_del();
					if(ret < 0) return ret;
				}
				{    int ret = r_e_ending();
					if(ret == 0) goto lab3;
					if(ret < 0) return ret;
				}
				break;
			case 4:
				{    int ret = r_R2();
					if(ret == 0) goto lab3;
					if(ret < 0) return ret;
				}
				{    int ret = slice_del();
					if(ret < 0) return ret;
				}
				break;
			case 5:
				{    int ret = r_R2();
					if(ret == 0) goto lab3;
					if(ret < 0) return ret;
				}
				if(!(I_e_found)) goto lab3;
				{    int ret = slice_del();
					if(ret < 0) return ret;
				}
				break;
		}
	lab3:
		c = l - m5;
	}
	{   int m9 = l - c; (void)m9;
		if(out_grouping_b_U(g_v_I, 73, 232, 0)) goto lab8;
		{   int m_test10 = l - c;
			if(c - 1 <= lb || p[c-1] >> 5 != 3 || !((2129954 >> (p[c-1] & 0x1f)) & 1)) goto lab8;
			if(!(find_among_b(s_pool, a_5, 4, 0, 0))) goto lab8;
			if(out_grouping_b_U(g_v, 97, 232, 0)) goto lab8;
			c = l - m_test10;
		}
		ket = c;
		{    int ret = skip_utf8(p, c, lb, 0, -1);
			if(ret < 0) goto lab8;
			c = ret;
		}
		bra = c;
		{    int ret = slice_del();
			if(ret < 0) return ret;
		}
	lab8:
		c = l - m9;
	}
	return 1;
}

int Xapian::InternalStemDutch::stem() {
	{   int c1 = c;
		{   int ret = r_prelude();
			if(ret < 0) return ret;
		}
		c = c1;
	}
	{   int c2 = c;
		{   int ret = r_mark_regions();
			if(ret < 0) return ret;
		}
		c = c2;
	}
	lb = c; c = l;

	
	{   int ret = r_standard_suffix();
		if(ret < 0) return ret;
	}
	c = lb;
	{   int c3 = c;
		{   int ret = r_postlude();
			if(ret < 0) return ret;
		}
		c = c3;
	}
	return 1;
}

Xapian::InternalStemDutch::InternalStemDutch()
    : I_p2(0), I_p1(0), I_e_found(0)
{
}

Xapian::InternalStemDutch::~InternalStemDutch()
{
}

std::string Xapian::InternalStemDutch::get_description() const { return "dutch.sbl"; }
