/** @file
 *  @brief Map string to language code
 */
/* Warning: This file is generated by collate-sbl - do not modify directly! */
/* Copyright (C) 2007,2012,2013,2015 Olly Betts
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 */
#ifndef XAPIAN_INCLUDED_SBL_DISPATCH_H
#define XAPIAN_INCLUDED_SBL_DISPATCH_H

enum sbl_code {
	NONE = 0
};

static const unsigned char tab[] = { 4, 1, 0, 1, 0, 1, 0, (0&255), (0>>8), (1 - 1), NONE, 'n', 'o', 'n', 'e' };

#define LANGSTRING ""

#endif
