/* Generated by Snowball 2.0.0 - https://snowballstem.org/ */


#include <xapian-internal.h>
#pragma hdrstop
#include "swedish.sbl.h"

#define s_0_0 (s_0_1 + 3)
#define s_0_1 s_0_23
#define s_0_2 (s_0_3 + 3)
static const symbol s_pool[] = {
#define s_0_3 0
'h', 'e', 't', 'e', 'r', 'n', 'a',
#define s_0_4 s_0_25
#define s_0_5 s_0_7
#define s_0_6 s_0_2
#define s_0_7 s_0_27
#define s_0_8 s_0_13
#define s_0_9 7
'a', 'r', 'n', 'e',
#define s_0_10 s_0_14
#define s_0_11 11
'a', 's', 't', 'e',
#define s_0_12 (s_0_13 + 3)
#define s_0_13 15
'a', 'n', 'd', 'e', 'n',
#define s_0_14 s_0_30
#define s_0_15 s_0_31
#define s_0_16 s_0_2
#define s_0_17 s_0_1
#define s_0_18 s_0_2
#define s_0_19 s_0_3
#define s_0_20 s_0_4
#define s_0_21 (s_0_11 + 1)
#define s_0_22 s_0_11
#define s_0_23 20
'a', 'r', 'n', 'a', 's',
#define s_0_24 25
'e', 'r', 'n', 'a', 's',
#define s_0_25 30
'o', 'r', 'n', 'a', 's',
#define s_0_26 (s_0_27 + 2)
#define s_0_27 35
'a', 'd', 'e', 's',
#define s_0_28 39
'a', 'n', 'd', 'e', 's',
#define s_0_29 (s_0_30 + 2)
#define s_0_30 44
'a', 'r', 'e', 'n', 's',
#define s_0_31 49
'h', 'e', 't', 'e', 'n', 's',
#define s_0_32 55
'e', 'r', 'n', 's',
#define s_0_33 59
'a', 't',
#define s_0_34 61
'a', 'n', 'd', 'e', 't',
#define s_0_35 s_0_3
#define s_0_36 s_0_11
#define s_1_0 66
'd', 'd',
#define s_1_1 68
'g', 'd',
#define s_1_2 70
'n', 'n',
#define s_1_3 72
'd', 't',
#define s_1_4 74
'g', 't',
#define s_1_5 76
'k', 't',
#define s_1_6 78
't', 't',
#define s_2_0 (s_2_1 + 1)
#define s_2_1 80
'l', 'i', 'g',
#define s_2_2 83
'e', 'l', 's',
#define s_2_3 86
'f', 'u', 'l', 'l', 't',
#define s_2_4 91
'l', 0xC3, 0xB6, 's', 't',
};


static const Among a_0[37] = {
/*  0 */ { 1, s_0_0, -1, 1},
/*  1 */ { 4, s_0_1, 0, 1},
/*  2 */ { 4, s_0_2, 0, 1},
/*  3 */ { 7, s_0_3, 2, 1},
/*  4 */ { 4, s_0_4, 0, 1},
/*  5 */ { 2, s_0_5, -1, 1},
/*  6 */ { 1, s_0_6, -1, 1},
/*  7 */ { 3, s_0_7, 6, 1},
/*  8 */ { 4, s_0_8, 6, 1},
/*  9 */ { 4, s_0_9, 6, 1},
/* 10 */ { 3, s_0_10, 6, 1},
/* 11 */ { 4, s_0_11, 6, 1},
/* 12 */ { 2, s_0_12, -1, 1},
/* 13 */ { 5, s_0_13, 12, 1},
/* 14 */ { 4, s_0_14, 12, 1},
/* 15 */ { 5, s_0_15, 12, 1},
/* 16 */ { 3, s_0_16, -1, 1},
/* 17 */ { 2, s_0_17, -1, 1},
/* 18 */ { 2, s_0_18, -1, 1},
/* 19 */ { 5, s_0_19, 18, 1},
/* 20 */ { 2, s_0_20, -1, 1},
/* 21 */ { 1, s_0_21, -1, 2},
/* 22 */ { 2, s_0_22, 21, 1},
/* 23 */ { 5, s_0_23, 22, 1},
/* 24 */ { 5, s_0_24, 22, 1},
/* 25 */ { 5, s_0_25, 22, 1},
/* 26 */ { 2, s_0_26, 21, 1},
/* 27 */ { 4, s_0_27, 26, 1},
/* 28 */ { 5, s_0_28, 26, 1},
/* 29 */ { 3, s_0_29, 21, 1},
/* 30 */ { 5, s_0_30, 29, 1},
/* 31 */ { 6, s_0_31, 29, 1},
/* 32 */ { 4, s_0_32, 21, 1},
/* 33 */ { 2, s_0_33, -1, 1},
/* 34 */ { 5, s_0_34, -1, 1},
/* 35 */ { 3, s_0_35, -1, 1},
/* 36 */ { 3, s_0_36, -1, 1}
};


static const Among a_1[7] = {
/*  0 */ { 2, s_1_0, -1, -1},
/*  1 */ { 2, s_1_1, -1, -1},
/*  2 */ { 2, s_1_2, -1, -1},
/*  3 */ { 2, s_1_3, -1, -1},
/*  4 */ { 2, s_1_4, -1, -1},
/*  5 */ { 2, s_1_5, -1, -1},
/*  6 */ { 2, s_1_6, -1, -1}
};


static const Among a_2[5] = {
/*  0 */ { 2, s_2_0, -1, 1},
/*  1 */ { 3, s_2_1, 0, 1},
/*  2 */ { 3, s_2_2, -1, 1},
/*  3 */ { 5, s_2_3, -1, 3},
/*  4 */ { 5, s_2_4, -1, 2}
};

static const uchar g_v[] = { 17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 32 };

static const uchar g_s_ending[] = { 119, 127, 149 };

static const symbol s_0[] = { 'l', 0xC3, 0xB6, 's' };
static const symbol s_1[] = { 'f', 'u', 'l', 'l' };

int Xapian::InternalStemSwedish::r_mark_regions() {
	I_p1 = l;
	{   int c_test1 = c;
		{    int ret = skip_utf8(p, c, 0, l, + 3);
			if(ret < 0) return 0;
			c = ret;
		}
		I_x = c;
		c = c_test1;
	}
	if(out_grouping_U(g_v, 97, 246, 1) < 0) return 0;
	{   
		int ret = in_grouping_U(g_v, 97, 246, 1);
		if(ret < 0) return 0;
		c += ret;
	}
	I_p1 = c;
	
	if(!(I_p1 < I_x)) goto lab0;
	I_p1 = I_x;
lab0:
	return 1;
}

int Xapian::InternalStemSwedish::r_main_suffix() {
	int among_var;

	{    int mlimit1;
		if(c < I_p1) return 0;
		mlimit1 = lb; lb = I_p1;
		ket = c;
		if(c <= lb || p[c-1] >> 5 != 3 || !((1851442 >> (p[c-1] & 0x1f)) & 1)) { lb = mlimit1; return 0; }
		among_var = find_among_b(s_pool, a_0, 37, 0, 0);
		if(!(among_var)) { lb = mlimit1; return 0; }
		bra = c;
		lb = mlimit1;
	}
	switch(among_var) {
		case 1:
			{    int ret = slice_del();
				if(ret < 0) return ret;
			}
			break;
		case 2:
			if(in_grouping_b_U(g_s_ending, 98, 121, 0)) return 0;
			{    int ret = slice_del();
				if(ret < 0) return ret;
			}
			break;
	}
	return 1;
}

int Xapian::InternalStemSwedish::r_consonant_pair() {

	{    int mlimit1;
		if(c < I_p1) return 0;
		mlimit1 = lb; lb = I_p1;
		{   int m2 = l - c; (void)m2;
			if(c - 1 <= lb || p[c-1] >> 5 != 3 || !((1064976 >> (p[c-1] & 0x1f)) & 1)) { lb = mlimit1; return 0; }
			if(!(find_among_b(s_pool, a_1, 7, 0, 0))) { lb = mlimit1; return 0; }
			c = l - m2;
			ket = c;
			{    int ret = skip_utf8(p, c, lb, 0, -1);
				if(ret < 0) { lb = mlimit1; return 0; }
				c = ret;
			}
			bra = c;
			{    int ret = slice_del();
				if(ret < 0) return ret;
			}
		}
		lb = mlimit1;
	}
	return 1;
}

int Xapian::InternalStemSwedish::r_other_suffix() {
	int among_var;

	{    int mlimit1;
		if(c < I_p1) return 0;
		mlimit1 = lb; lb = I_p1;
		ket = c;
		if(c - 1 <= lb || p[c-1] >> 5 != 3 || !((1572992 >> (p[c-1] & 0x1f)) & 1)) { lb = mlimit1; return 0; }
		among_var = find_among_b(s_pool, a_2, 5, 0, 0);
		if(!(among_var)) { lb = mlimit1; return 0; }
		bra = c;
		switch(among_var) {
			case 1:
				{    int ret = slice_del();
					if(ret < 0) return ret;
				}
				break;
			case 2:
				{    int ret = slice_from_s(4, s_0);
					if(ret < 0) return ret;
				}
				break;
			case 3:
				{    int ret = slice_from_s(4, s_1);
					if(ret < 0) return ret;
				}
				break;
		}
		lb = mlimit1;
	}
	return 1;
}

int Xapian::InternalStemSwedish::stem() {
	{   int c1 = c;
		{   int ret = r_mark_regions();
			if(ret < 0) return ret;
		}
		c = c1;
	}
	lb = c; c = l;

	{   int m2 = l - c; (void)m2;
		{   int ret = r_main_suffix();
			if(ret < 0) return ret;
		}
		c = l - m2;
	}
	{   int m3 = l - c; (void)m3;
		{   int ret = r_consonant_pair();
			if(ret < 0) return ret;
		}
		c = l - m3;
	}
	{   int m4 = l - c; (void)m4;
		{   int ret = r_other_suffix();
			if(ret < 0) return ret;
		}
		c = l - m4;
	}
	c = lb;
	return 1;
}

Xapian::InternalStemSwedish::InternalStemSwedish()
    : I_x(0), I_p1(0)
{
}

Xapian::InternalStemSwedish::~InternalStemSwedish()
{
}

std::string Xapian::InternalStemSwedish::get_description() const { return "swedish.sbl"; }
