/*
 * Summary: interface for all global variables of the library
 * Description: all the global variables and thread handling for
 *   those variables is handled by this module.
 *
 * The bottom of this file is automatically generated by build_glob.py
 * based on the description file global.data
 *
 * Copy: See Copyright for the status of this software.
 *
 * Author: Gary Pennington <Gary.Pennington@uk.sun.com>, Daniel Veillard
 */

#ifndef __XML_GLOBALS_H
#define __XML_GLOBALS_H

#include <libxml/xmlversion.h>
#include <libxml/parser.h>
#include <libxml/xmlmemory.h>
#include <libxml/encoding.h>

//#ifdef __cplusplus
//extern "C" {
//#endif

void xmlInitGlobals();
void xmlCleanupGlobals();
/**
 * xmlParserInputBufferCreateFilenameFunc:
 * @URI: the URI to read from
 * @enc: the requested source encoding
 *
 * Signature for the function doing the lookup for a suitable input method
 * corresponding to an URI.
 *
 * Returns the new xmlParserInputBufferPtr in case of success or NULL if no method was found.
 */
typedef xmlParserInputBuffer * (*xmlParserInputBufferCreateFilenameFunc)(const char *URI, xmlCharEncoding enc);
/**
 * xmlOutputBufferCreateFilenameFunc:
 * @URI: the URI to write to
 * @enc: the requested target encoding
 *
 * Signature for the function doing the lookup for a suitable output method
 * corresponding to an URI.
 *
 * Returns the new xmlOutputBufferPtr in case of success or NULL if no method was found.
 */
typedef xmlOutputBuffer * (*xmlOutputBufferCreateFilenameFunc) (const char *URI, xmlCharEncodingHandler * encoder, int compression);

xmlParserInputBufferCreateFilenameFunc xmlParserInputBufferCreateFilenameDefault (xmlParserInputBufferCreateFilenameFunc func);
xmlOutputBufferCreateFilenameFunc xmlOutputBufferCreateFilenameDefault (xmlOutputBufferCreateFilenameFunc func);
/*
 * Externally global symbols which need to be protected for backwards compatibility support.
 */
#undef docbDefaultSAXHandler
#undef htmlDefaultSAXHandler
#undef oldXMLWDcompatibility
#undef xmlBufferAllocScheme
#undef xmlDefaultBufferSize
#undef xmlDefaultSAXHandler
#undef xmlDefaultSAXLocator
#undef xmlDoValidityCheckingDefaultValue
// @sobolev #undef xmlFree
#undef	xmlGenericError
#undef	xmlStructuredError
#undef	xmlGenericErrorContext
#undef	xmlStructuredErrorContext
#undef	xmlGetWarningsDefaultValue
#undef	xmlIndentTreeOutput
#undef  xmlTreeIndentString
#undef	xmlKeepBlanksDefaultValue
#undef	xmlLineNumbersDefaultValue
#undef	xmlLoadExtDtdDefaultValue
#undef	xmlMalloc
#undef	xmlMallocAtomic
#undef	xmlMemStrdup_Removed
#undef	xmlParserDebugEntities
#undef	xmlParserVersion
#undef	xmlPedanticParserDefaultValue
#undef	xmlRealloc
#undef	xmlSaveNoEmptyTags
#undef	xmlSubstituteEntitiesDefaultValue
#undef  xmlRegisterNodeDefaultValue
#undef  xmlDeregisterNodeDefaultValue
#undef  xmlLastError
#undef  xmlParserInputBufferCreateFilenameValue
#undef  xmlOutputBufferCreateFilenameValue
/**
 * xmlRegisterNodeFunc:
 * @node: the current node
 *
 * Signature for the registration callback of a created node
 */
typedef void (*xmlRegisterNodeFunc)(xmlNode * P_Node);
/**
 * xmlDeregisterNodeFunc:
 * @node: the current node
 *
 * Signature for the deregistration callback of a discarded node
 */
typedef void (*xmlDeregisterNodeFunc)(xmlNode * P_Node);

//typedef struct _xmlGlobalState xmlGlobalState;

struct xmlGlobalState {
	const char *xmlParserVersion;
	xmlSAXLocator xmlDefaultSAXLocator;
	xmlSAXHandlerV1 xmlDefaultSAXHandler;
	xmlSAXHandlerV1 docbDefaultSAXHandler;
	xmlSAXHandlerV1 htmlDefaultSAXHandler;
	xmlFreeFunc xmlFree_; // @sobolev xmlFree-->xmlFree_
	//xmlMallocFunc xmlMalloc_;
	//xmlStrdupFunc xmlMemStrdup_Removed;
	//xmlReallocFunc xmlRealloc_;
	xmlGenericErrorFunc xmlGenericError;
	xmlStructuredErrorFunc xmlStructuredError;
	void *xmlGenericErrorContext;
	int oldXMLWDcompatibility;
	xmlBufferAllocationScheme xmlBufferAllocScheme;
	int xmlDefaultBufferSize;
	int xmlSubstituteEntitiesDefaultValue;
	int xmlDoValidityCheckingDefaultValue;
	int xmlGetWarningsDefaultValue;
	int xmlKeepBlanksDefaultValue;
	int xmlLineNumbersDefaultValue;
	int xmlLoadExtDtdDefaultValue;
	int xmlParserDebugEntities;
	int xmlPedanticParserDefaultValue;
	int xmlSaveNoEmptyTags;
	int xmlIndentTreeOutput;
	const char *xmlTreeIndentString;
	xmlRegisterNodeFunc xmlRegisterNodeDefaultValue;
	xmlDeregisterNodeFunc xmlDeregisterNodeDefaultValue;
	//xmlMallocFunc xmlMallocAtomic_;
	xmlError xmlLastError;
	xmlParserInputBufferCreateFilenameFunc xmlParserInputBufferCreateFilenameValue;
	xmlOutputBufferCreateFilenameFunc xmlOutputBufferCreateFilenameValue;
	void * xmlStructuredErrorContext;
};

//typedef xmlGlobalState * xmlGlobalStatePtr;

void xmlInitializeGlobalState(xmlGlobalState * gs);
void xmlThrDefSetGenericErrorFunc(void *ctx, xmlGenericErrorFunc handler);
void xmlThrDefSetStructuredErrorFunc(void *ctx, xmlStructuredErrorFunc handler);
xmlRegisterNodeFunc xmlRegisterNodeDefault(xmlRegisterNodeFunc func);
xmlRegisterNodeFunc xmlThrDefRegisterNodeDefault(xmlRegisterNodeFunc func);
xmlDeregisterNodeFunc xmlDeregisterNodeDefault(xmlDeregisterNodeFunc func);
xmlDeregisterNodeFunc xmlThrDefDeregisterNodeDefault(xmlDeregisterNodeFunc func);
xmlOutputBufferCreateFilenameFunc xmlThrDefOutputBufferCreateFilenameDefault(xmlOutputBufferCreateFilenameFunc func);
xmlParserInputBufferCreateFilenameFunc xmlThrDefParserInputBufferCreateFilenameDefault(xmlParserInputBufferCreateFilenameFunc func);

/** DOC_DISABLE */
/*
 * In general the memory allocation entry points are not kept
 * thread specific but this can be overridden by LIBXML_THREAD_ALLOC_ENABLED
 *  - xmlMalloc
 *  - xmlMallocAtomic
 *  - xmlRealloc
 *  - xmlMemStrdup
 *  - xmlFree
 */
#ifdef LIBXML_THREAD_ALLOC_ENABLED
	#ifdef LIBXML_THREAD_ENABLED
		 xmlMallocFunc * __xmlMalloc();
		//#define xmlMalloc_(*(__xmlMalloc()))
	#else
		//XMLPUBVAR xmlMallocFunc xmlMalloc_;
	#endif
	#ifdef LIBXML_THREAD_ENABLED
		 xmlMallocFunc * __xmlMallocAtomic();
		//#define xmlMallocAtomic_(*(__xmlMallocAtomic()))
	#else
		//XMLPUBVAR xmlMallocFunc xmlMallocAtomic_;
	#endif
	#ifdef LIBXML_THREAD_ENABLED
		 xmlReallocFunc * __xmlRealloc();
		#define xmlRealloc (*(__xmlRealloc()))
	#else
		XMLPUBVAR xmlReallocFunc xmlRealloc;
	#endif
	#ifdef LIBXML_THREAD_ENABLED
		 xmlFreeFunc * __xmlFree();
		// @sobolev #define xmlFree_ (*(__xmlFree()))
	#else
		// @sobolev XMLPUBVAR xmlFreeFunc xmlFree_;
	#endif
	#ifdef LIBXML_THREAD_ENABLED
		 xmlStrdupFunc * __xmlMemStrdup();
		//#define xmlMemStrdup_Removed (*(__xmlMemStrdup()))
	#else
		//XMLPUBVAR xmlStrdupFunc xmlMemStrdup_Removed;
	#endif
#else /* !LIBXML_THREAD_ALLOC_ENABLED */
	//XMLPUBVAR xmlMallocFunc xmlMalloc_;
	//XMLPUBVAR xmlMallocFunc xmlMallocAtomic_;
	//XMLPUBVAR xmlReallocFunc xmlRealloc_;
	// @sobolev XMLPUBVAR xmlFreeFunc xmlFree_;
	//XMLPUBVAR xmlStrdupFunc xmlMemStrdup_Removed;
#endif /* LIBXML_THREAD_ALLOC_ENABLED */
#ifdef LIBXML_DOCB_ENABLED
	 xmlSAXHandlerV1 * __docbDefaultSAXHandler();
	#ifdef LIBXML_THREAD_ENABLED
		#define docbDefaultSAXHandler (*(__docbDefaultSAXHandler()))
	#else
		XMLPUBVAR xmlSAXHandlerV1 docbDefaultSAXHandler;
	#endif
#endif
#ifdef LIBXML_HTML_ENABLED
	xmlSAXHandlerV1 * __htmlDefaultSAXHandler();
	#ifdef LIBXML_THREAD_ENABLED
		#define htmlDefaultSAXHandler (*(__htmlDefaultSAXHandler()))
	#else
		XMLPUBVAR xmlSAXHandlerV1 htmlDefaultSAXHandler;
	#endif
#endif

xmlError * __xmlLastError();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlLastError (*(__xmlLastError()))
#else
	XMLPUBVAR xmlError xmlLastError;
#endif

/*
 * Everything starting from the line below is
 * Automatically generated by build_glob.py.
 * Do not modify the previous line.
 */


int * __oldXMLWDcompatibility();
#ifdef LIBXML_THREAD_ENABLED
	#define oldXMLWDcompatibility (*(__oldXMLWDcompatibility()))
#else
	XMLPUBVAR int oldXMLWDcompatibility;
#endif

xmlBufferAllocationScheme * __xmlBufferAllocScheme();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlBufferAllocScheme (*(__xmlBufferAllocScheme()))
#else
	XMLPUBVAR xmlBufferAllocationScheme xmlBufferAllocScheme;
#endif
xmlBufferAllocationScheme xmlThrDefBufferAllocScheme(xmlBufferAllocationScheme v);
int * __xmlDefaultBufferSize();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlDefaultBufferSize (*(__xmlDefaultBufferSize()))
#else
	XMLPUBVAR int xmlDefaultBufferSize;
#endif
int xmlThrDefDefaultBufferSize(int v);
xmlSAXHandlerV1 * __xmlDefaultSAXHandler();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlDefaultSAXHandler (*(__xmlDefaultSAXHandler()))
#else
	XMLPUBVAR xmlSAXHandlerV1 xmlDefaultSAXHandler;
#endif
xmlSAXLocator * __xmlDefaultSAXLocator();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlDefaultSAXLocator (*(__xmlDefaultSAXLocator()))
#else
	XMLPUBVAR xmlSAXLocator xmlDefaultSAXLocator;
#endif
int * __xmlDoValidityCheckingDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlDoValidityCheckingDefaultValue (*(__xmlDoValidityCheckingDefaultValue()))
#else
	XMLPUBVAR int xmlDoValidityCheckingDefaultValue;
#endif
int xmlThrDefDoValidityCheckingDefaultValue(int v);
xmlGenericErrorFunc * __xmlGenericError();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlGenericError (*(__xmlGenericError()))
#else
	XMLPUBVAR xmlGenericErrorFunc xmlGenericError;
#endif

xmlStructuredErrorFunc * __xmlStructuredError();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlStructuredError (*(__xmlStructuredError()))
#else
	XMLPUBVAR xmlStructuredErrorFunc xmlStructuredError;
#endif
void * * __xmlGenericErrorContext();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlGenericErrorContext (*(__xmlGenericErrorContext()))
#else
	XMLPUBVAR void * xmlGenericErrorContext;
#endif
void * * __xmlStructuredErrorContext();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlStructuredErrorContext (*(__xmlStructuredErrorContext()))
#else
	XMLPUBVAR void * xmlStructuredErrorContext;
#endif
int * __xmlGetWarningsDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlGetWarningsDefaultValue (*(__xmlGetWarningsDefaultValue()))
#else
	XMLPUBVAR int xmlGetWarningsDefaultValue;
#endif
int xmlThrDefGetWarningsDefaultValue(int v);
int * __xmlIndentTreeOutput();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlIndentTreeOutput (*(__xmlIndentTreeOutput()))
#else
	XMLPUBVAR int xmlIndentTreeOutput;
#endif
int xmlThrDefIndentTreeOutput(int v);
const char * * __xmlTreeIndentString();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlTreeIndentString (*(__xmlTreeIndentString()))
#else
XMLPUBVAR const char * xmlTreeIndentString;
#endif
const char * xmlThrDefTreeIndentString(const char * v);
int * __xmlKeepBlanksDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlKeepBlanksDefaultValue (*(__xmlKeepBlanksDefaultValue()))
#else
	XMLPUBVAR int xmlKeepBlanksDefaultValue;
#endif
int xmlThrDefKeepBlanksDefaultValue(int v);
int * __xmlLineNumbersDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlLineNumbersDefaultValue (*(__xmlLineNumbersDefaultValue()))
#else
	XMLPUBVAR int xmlLineNumbersDefaultValue;
#endif
int xmlThrDefLineNumbersDefaultValue(int v);
int * __xmlLoadExtDtdDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlLoadExtDtdDefaultValue (*(__xmlLoadExtDtdDefaultValue()))
#else
	XMLPUBVAR int xmlLoadExtDtdDefaultValue;
#endif
int xmlThrDefLoadExtDtdDefaultValue(int v);
int * __xmlParserDebugEntities();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlParserDebugEntities (*(__xmlParserDebugEntities()))
#else
	XMLPUBVAR int xmlParserDebugEntities;
#endif
int xmlThrDefParserDebugEntities(int v);
const char * * __xmlParserVersion();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlParserVersion (*(__xmlParserVersion()))
#else
	XMLPUBVAR const char * xmlParserVersion;
#endif

int * __xmlPedanticParserDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlPedanticParserDefaultValue (*(__xmlPedanticParserDefaultValue()))
#else
	XMLPUBVAR int xmlPedanticParserDefaultValue;
#endif
int xmlThrDefPedanticParserDefaultValue(int v);
int * __xmlSaveNoEmptyTags();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlSaveNoEmptyTags (*(__xmlSaveNoEmptyTags()))
#else
	XMLPUBVAR int xmlSaveNoEmptyTags;
#endif
int xmlThrDefSaveNoEmptyTags(int v);
int * __xmlSubstituteEntitiesDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlSubstituteEntitiesDefaultValue (*(__xmlSubstituteEntitiesDefaultValue()))
#else
	XMLPUBVAR int xmlSubstituteEntitiesDefaultValue;
#endif
int xmlThrDefSubstituteEntitiesDefaultValue(int v);
xmlRegisterNodeFunc * __xmlRegisterNodeDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlRegisterNodeDefaultValue (*(__xmlRegisterNodeDefaultValue()))
#else
	XMLPUBVAR xmlRegisterNodeFunc xmlRegisterNodeDefaultValue;
#endif

xmlDeregisterNodeFunc * __xmlDeregisterNodeDefaultValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlDeregisterNodeDefaultValue (*(__xmlDeregisterNodeDefaultValue()))
#else
	XMLPUBVAR xmlDeregisterNodeFunc xmlDeregisterNodeDefaultValue;
#endif
xmlParserInputBufferCreateFilenameFunc * __xmlParserInputBufferCreateFilenameValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlParserInputBufferCreateFilenameValue (*(__xmlParserInputBufferCreateFilenameValue()))
#else
	XMLPUBVAR xmlParserInputBufferCreateFilenameFunc xmlParserInputBufferCreateFilenameValue;
#endif
xmlOutputBufferCreateFilenameFunc * __xmlOutputBufferCreateFilenameValue();
#ifdef LIBXML_THREAD_ENABLED
	#define xmlOutputBufferCreateFilenameValue (*(__xmlOutputBufferCreateFilenameValue()))
#else
	XMLPUBVAR xmlOutputBufferCreateFilenameFunc xmlOutputBufferCreateFilenameValue;
#endif

//#ifdef __cplusplus
//}
//#endif
#endif /* __XML_GLOBALS_H */
