/* DO NOT EDIT: automatically built by dist/s_include. */
#ifndef	_rep_ext_h_
#define	_rep_ext_h_

#if defined(__cplusplus)
extern "C" {
#endif

int __rep_bulk_marshal __P((ENV *, __rep_bulk_args *, uint8 *, size_t, size_t *));
int __rep_bulk_unmarshal __P((ENV *, __rep_bulk_args *, uint8 *, size_t, uint8 **));
int __rep_control_marshal __P((ENV *, __rep_control_args *, uint8 *, size_t, size_t *));
int __rep_control_unmarshal __P((ENV *, __rep_control_args *, uint8 *, size_t, uint8 **));
int __rep_egen_marshal __P((ENV *, __rep_egen_args *, uint8 *, size_t, size_t *));
int __rep_egen_unmarshal __P((ENV *, __rep_egen_args *, uint8 *, size_t, uint8 **));
int __rep_fileinfo_marshal __P((ENV *, __rep_fileinfo_args *, uint8 *, size_t, size_t *));
int __rep_fileinfo_unmarshal __P((ENV *, __rep_fileinfo_args **, uint8 *, size_t, uint8 **));
int __rep_fileinfo_v7_marshal __P((ENV *, __rep_fileinfo_v7_args *, uint8 *, size_t, size_t *));
int __rep_fileinfo_v7_unmarshal __P((ENV *, __rep_fileinfo_v7_args **, uint8 *, size_t, uint8 **));
int __rep_fileinfo_v6_marshal __P((ENV *, __rep_fileinfo_v6_args *, uint8 *, size_t, size_t *));
int __rep_fileinfo_v6_unmarshal __P((ENV *, __rep_fileinfo_v6_args **, uint8 *, size_t, uint8 **));
int __rep_grant_info_marshal __P((ENV *, __rep_grant_info_args *, uint8 *, size_t, size_t *));
int __rep_grant_info_unmarshal __P((ENV *, __rep_grant_info_args *, uint8 *, size_t, uint8 **));
int __rep_logreq_marshal __P((ENV *, __rep_logreq_args *, uint8 *, size_t, size_t *));
int __rep_logreq_unmarshal __P((ENV *, __rep_logreq_args *, uint8 *, size_t, uint8 **));
int __rep_newfile_marshal __P((ENV *, __rep_newfile_args *, uint8 *, size_t, size_t *));
int __rep_newfile_unmarshal __P((ENV *, __rep_newfile_args *, uint8 *, size_t, uint8 **));
int __rep_update_marshal __P((ENV *, __rep_update_args *, uint8 *, size_t, size_t *));
int __rep_update_unmarshal __P((ENV *, __rep_update_args **, uint8 *, size_t, uint8 **));
int __rep_vote_info_marshal __P((ENV *, __rep_vote_info_args *, uint8 *, size_t, size_t *));
int __rep_vote_info_unmarshal __P((ENV *, __rep_vote_info_args *, uint8 *, size_t, uint8 **));
int __rep_vote_info_v5_marshal __P((ENV *, __rep_vote_info_v5_args *, uint8 *, size_t, size_t *));
int __rep_vote_info_v5_unmarshal __P((ENV *, __rep_vote_info_v5_args *, uint8 *, size_t, uint8 **));
void __rep_lsn_hist_key_marshal __P((ENV *, __rep_lsn_hist_key_args *, uint8 *));
int __rep_lsn_hist_key_unmarshal __P((ENV *, __rep_lsn_hist_key_args *, uint8 *, size_t, uint8 **));
void __rep_lsn_hist_data_marshal __P((ENV *, __rep_lsn_hist_data_args *, uint8 *));
int __rep_lsn_hist_data_unmarshal __P((ENV *, __rep_lsn_hist_data_args *, uint8 *, size_t, uint8 **));
void __rep_blob_update_req_marshal __P((ENV *, __rep_blob_update_req_args *, uint8 *));
int __rep_blob_update_req_unmarshal __P((ENV *, __rep_blob_update_req_args *, uint8 *, size_t, uint8 **));
void __rep_blob_update_req_v8_marshal __P((ENV *, __rep_blob_update_req_v8_args *, uint8 *));
int __rep_blob_update_req_v8_unmarshal __P((ENV *, __rep_blob_update_req_v8_args *, uint8 *, size_t, uint8 **));
void __rep_blob_update_marshal __P((ENV *, __rep_blob_update_args *, uint8 *));
int __rep_blob_update_unmarshal __P((ENV *, __rep_blob_update_args *, uint8 *, size_t, uint8 **));
void __rep_blob_file_marshal __P((ENV *, __rep_blob_file_args *, uint8 *));
int __rep_blob_file_unmarshal __P((ENV *, __rep_blob_file_args *, uint8 *, size_t, uint8 **));
void __rep_blob_chunk_marshal __P((ENV *, __rep_blob_chunk_args *, uint8 *));
int __rep_blob_chunk_unmarshal __P((ENV *, __rep_blob_chunk_args *, uint8 *, size_t, uint8 **));
void __rep_blob_chunk_req_marshal __P((ENV *, __rep_blob_chunk_req_args *, uint8 *));
int __rep_blob_chunk_req_unmarshal __P((ENV *, __rep_blob_chunk_req_args *, uint8 *, size_t, uint8 **));
int __rep_update_req __P((ENV *, __rep_control_args *));
int __rep_blob_update_req __P((ENV *, int, DB_THREAD_INFO *, DBT *));
int __rep_page_req __P((ENV *, DB_THREAD_INFO *, int, __rep_control_args *, DBT *));
int __rep_update_setup __P((ENV *, int, __rep_control_args *, DBT *, time_t, DB_LSN *));
int __rep_blob_update __P((ENV *, int, DB_THREAD_INFO *, DBT *));
int __rep_blob_allreq __P((ENV *, int, DBT *));
int __rep_bulk_page __P((ENV *, DB_THREAD_INFO *, int, __rep_control_args *, DBT *));
int __rep_page __P((ENV *, DB_THREAD_INFO *, int, __rep_control_args *, DBT *));
int __rep_blob_chunk __P((ENV *, int, DB_THREAD_INFO *, DBT *));
int __rep_init_cleanup __P((ENV *, REP *, int));
int __rep_blob_chunk_req __P((ENV *, int, DBT *));
int __rep_pggap_req __P((ENV *, REP *, __rep_fileinfo_args *, uint32));
int __rep_blob_rereq __P((ENV *, REP *, uint32));
int __rep_finfo_alloc __P((ENV *, __rep_fileinfo_args *, __rep_fileinfo_args **));
int __rep_remove_init_file __P((ENV *));
int __rep_reset_init __P((ENV *));
int __rep_elect_pp __P((DB_ENV *, uint32, uint32, uint32));
int __rep_elect_int __P((ENV *, uint32, uint32, uint32));
int __rep_vote1 __P((ENV *, __rep_control_args *, DBT *, int));
int __rep_vote2 __P((ENV *, DBT *, int));
int __rep_update_grant __P((ENV *, db_timespec *));
int __rep_islease_granted __P((ENV *));
int __rep_lease_table_alloc __P((ENV *, uint32));
int __rep_lease_grant __P((ENV *, __rep_control_args *, DBT *, int));
int __rep_lease_check __P((ENV *, int));
int __rep_lease_refresh __P((ENV *));
int __rep_lease_expire __P((ENV *));
db_timeout_t __rep_lease_waittime __P((ENV *));
int __rep_allreq __P((ENV *, __rep_control_args *, int));
int __rep_log __P((ENV *, DB_THREAD_INFO *, __rep_control_args *, DBT *, int, time_t, DB_LSN *, DB_LSN *));
int __rep_bulk_log __P((ENV *, DB_THREAD_INFO *, __rep_control_args *, DBT *, time_t, DB_LSN *, DB_LSN *));
int __rep_logreq __P((ENV *, __rep_control_args *, DBT *, int));
int __rep_loggap_req __P((ENV *, REP *, DB_LSN *, uint32));
int __rep_logready __P((ENV *, REP *, time_t, DB_LSN *));
int __rep_env_create __P((DB_ENV *));
void __rep_env_destroy __P((DB_ENV *));
int __rep_get_config __P((DB_ENV *, uint32, int *));
int __rep_set_config __P((DB_ENV *, uint32, int));
int __rep_start_pp __P((DB_ENV *, DBT *, uint32));
int __rep_start_int __P((ENV *, DBT *, uint32, uint32));
int __rep_open_sysdb __P((ENV *, DB_THREAD_INFO *, DB_TXN *, const char *, uint32, DB **));
int __rep_client_dbinit __P((ENV *, int, repdb_t));
int  __rep_blob_cmp __P((DB *, const DBT *, const DBT *, size_t *));
int  __rep_offset_cmp __P((DB *, const DBT *, const DBT *, size_t *));
int __rep_get_limit __P((DB_ENV *, uint32 *, uint32 *));
int __rep_set_limit __P((DB_ENV *, uint32, uint32));
int __rep_set_nsites_pp __P((DB_ENV *, uint32));
int __rep_set_nsites_int __P((ENV *, uint32));
int __rep_get_nsites __P((DB_ENV *, uint32 *));
int __rep_set_priority_pp __P((DB_ENV *, uint32));
int __rep_set_priority_int __P((ENV *, uint32));
int __rep_get_priority __P((DB_ENV *, uint32 *));
int __rep_set_timeout_pp __P((DB_ENV *, int, db_timeout_t));
int __rep_set_timeout_int __P((ENV *, int, db_timeout_t));
int __rep_get_timeout __P((DB_ENV *, int, db_timeout_t *));
int __rep_get_request __P((DB_ENV *, db_timeout_t *, db_timeout_t *));
int __rep_set_request __P((DB_ENV *, db_timeout_t, db_timeout_t));
int __rep_set_view __P((DB_ENV *, int (*)(DB_ENV *, const char *, int *, uint32)));
int __rep_call_partial __P((ENV *, const char *, int *, uint32, DELAYED_BLOB_LIST **));
int __rep_set_transport_pp __P((DB_ENV *, int, int (*)(DB_ENV *, const DBT *, const DBT *, const DB_LSN *, int, uint32)));
int __rep_set_transport_int __P((ENV *, int, int (*)(DB_ENV *, const DBT *, const DBT *, const DB_LSN *, int, uint32)));
int __rep_get_clockskew __P((DB_ENV *, uint32 *, uint32 *));
int __rep_set_clockskew __P((DB_ENV *, uint32, uint32));
int __rep_flush_pp __P((DB_ENV *));
int __rep_flush_int __P((ENV *));
int __rep_sync __P((DB_ENV *, uint32));
int __rep_txn_applied __P((ENV *, DB_THREAD_INFO *, DB_COMMIT_INFO *, db_timeout_t));
int __rep_read_lsn_history __P((ENV *, DB_THREAD_INFO *, DB_TXN **, DBC **, uint32, __rep_lsn_hist_data_args *, struct rep_waitgoal *, uint32, int));
int __rep_process_message_pp __P((DB_ENV *, DBT *, DBT *, int, DB_LSN *));
int __rep_process_message_int __P((ENV *, DBT *, DBT *, int, DB_LSN *, DB_LSN *));
int __rep_apply __P((ENV *, DB_THREAD_INFO *, __rep_control_args *, DBT *, DB_LSN *, int *, DB_LSN *, DB_LSN *));
int __rep_process_txn __P((ENV *, DBT *));
int __rep_resend_req __P((ENV *, int));
int __rep_check_doreq __P((ENV *, REP *));
int __rep_check_missing __P((ENV *, uint32, DB_LSN *));
int __rep_open __P((ENV *));
int __rep_close_diagfiles __P((ENV *));
int __rep_env_refresh __P((ENV *));
int __rep_env_close __P((ENV *));
int __rep_preclose __P((ENV *));
int __rep_closefiles __P((ENV *));
int __rep_write_egen __P((ENV *, REP *, uint32));
int __rep_write_gen __P((ENV *, REP *, uint32));
int __rep_check_view __P((ENV *));
int __rep_stat_pp __P((DB_ENV *, DB_REP_STAT **, uint32));
int __rep_stat_print_pp __P((DB_ENV *, uint32));
int __rep_stat_print __P((ENV *, uint32));
int __rep_bulk_message __P((ENV *, REP_BULK *, REP_THROTTLE *, DB_LSN *, const DBT *, uint32));
int __rep_send_bulk __P((ENV *, REP_BULK *, uint32));
int __rep_bulk_alloc __P((ENV *, REP_BULK *, int, uintptr_t *, uint32 *, uint32));
int __rep_bulk_free __P((ENV *, REP_BULK *, uint32));
int __rep_send_message __P((ENV *, int, uint32, DB_LSN *, const DBT *, uint32, uint32));
int __rep_new_master __P((ENV *, __rep_control_args *, int));
void __rep_elect_done __P((ENV *, REP *));
int __env_rep_enter __P((ENV *, int));
int __env_db_rep_exit __P((ENV *));
int __db_rep_enter __P((DB *, int, int, int));
int __op_handle_enter __P((ENV *));
int __op_rep_enter __P((ENV *, int, int));
int __op_rep_exit __P((ENV *));
int __archive_rep_enter __P((ENV *));
int __archive_rep_exit __P((ENV *));
int __rep_lockout_archive __P((ENV *, REP *));
int __rep_lockout_api __P((ENV *, REP *));
int __rep_take_apilockout __P((ENV *));
int __rep_clear_apilockout __P((ENV *));
int __rep_lockout_apply __P((ENV *, REP *, uint32));
int __rep_lockout_msg __P((ENV *, REP *, uint32));
int __rep_send_throttle __P((ENV *, int, REP_THROTTLE *, uint32, uint32));
uint32 __rep_msg_to_old __P((uint32, uint32));
uint32 __rep_msg_from_old __P((uint32, uint32));
int __rep_print_system __P((ENV *, uint32, const char *, ...)) __attribute__ ((__format__ (__printf__, 3, 4)));
int __rep_print __P((ENV *, uint32, const char *, ...)) __attribute__ ((__format__ (__printf__, 3, 4)));
void __rep_print_message __P((ENV *, int, __rep_control_args *, char *, uint32));
void __rep_fire_event __P((ENV *, uint32, void *));
void __rep_msg __P((const ENV *, const char *));
int __rep_notify_threads __P((ENV *, rep_waitreason_t));
int __rep_check_goal __P((ENV *, struct rep_waitgoal *));
int __rep_log_backup __P((ENV *, DB_LOGC *, DB_LSN *, uint32));
int __rep_get_maxpermlsn __P((ENV *, DB_LSN *));
int __rep_is_internal_rep_file __P((char *));
int __rep_get_datagen __P((ENV *, uint32 *));
int __rep_become_readonly_master __P((ENV *, uint32 *, DB_LSN *));
int __rep_get_lsnhist_data __P((ENV *, DB_THREAD_INFO *, uint32, __rep_lsn_hist_data_args *));
int __rep_verify __P((ENV *, __rep_control_args *, DBT *, int, time_t));
int __rep_verify_fail __P((ENV *, __rep_control_args *));
int __rep_verify_req __P((ENV *, __rep_control_args *, int));
int __rep_dorecovery __P((ENV *, DB_LSN *, DB_LSN *));
int __rep_verify_match __P((ENV *, DB_LSN *, time_t));

#if defined(__cplusplus)
}
#endif
#endif /* !_rep_ext_h_ */
