/* DO NOT EDIT: automatically built by dist/s_include. */
#ifndef	_log_ext_h_
#define	_log_ext_h_

#if defined(__cplusplus)
extern "C" {
#endif

int __log_open(ENV *);
int __log_find(DB_LOG *, int, uint32 *, logfile_validity *);
int __log_valid(DB_LOG *, uint32, int, DB_FH **, uint32, logfile_validity *, uint32 *);
int __log_env_refresh(ENV *);
int __log_get_cached_ckp_lsn(ENV *, DB_LSN *);
uint32 __log_region_mutex_count(ENV *);
uint32 __log_region_mutex_max(ENV *);
size_t	__log_region_size(ENV *);
size_t	__log_region_max(ENV *);
int __log_vtruncate(ENV *, DB_LSN *, DB_LSN *, DB_LSN *);
int __log_is_outdated(ENV *, uint32, int *);
int __log_zero(ENV *, DB_LSN *);
int __log_inmem_lsnoff(DB_LOG *, DB_LSN *, size_t *);
int __log_inmem_newfile(DB_LOG *, uint32);
int __log_inmem_chkspace(DB_LOG *, size_t);
void __log_inmem_copyout(DB_LOG *, size_t, void *, size_t);
void __log_inmem_copyin(DB_LOG *, size_t, void *, size_t);
void __log_set_version(ENV *, uint32);
int __log_get_oldversion(ENV *, uint32 *);
int __log_archive_pp(DB_ENV *, char **[], uint32);
int __log_get_stable_lsn(ENV *, DB_LSN *, int);
void __log_autoremove(ENV *);
int __log_check_page_lsn(ENV *, DB *, DB_LSN *);
int __log_printf_capi(DB_ENV *, DB_TXN *, const char *, ...) __attribute__((__format__ (__printf__, 3, 4)));
int __log_printf_pp(DB_ENV *, DB_TXN *, const char *, va_list);
int __log_printf(ENV *, DB_TXN *, const char *, ...) __attribute__((__format__ (__printf__, 3, 4)));
int __log_cursor_pp(DB_ENV *, DB_LOGC **, uint32);
int FASTCALL __log_cursor(ENV *, DB_LOGC **);
int FASTCALL __logc_close(DB_LOGC *);
int __logc_version(DB_LOGC *, uint32 *);
int FASTCALL __logc_get(DB_LOGC *, DB_LSN *, DBT *, uint32);
void __log_hdrswap(HDR *, int);
void __log_persistswap(LOGP *);
int __log_read_record_pp(DB_ENV *, DB **, void *, void *, DB_LOG_RECSPEC *, uint32, void **);
int FASTCALL __log_read_record(ENV *, DB **, void *, void *, DB_LOG_RECSPEC *, uint32, void **);
int __log_env_create(DB_ENV *);
void __log_env_destroy(DB_ENV *);
int __log_get_lg_bsize(DB_ENV *, uint32 *);
int __log_set_lg_bsize(DB_ENV *, uint32);
int __log_get_lg_filemode(DB_ENV *, int *);
int __log_set_lg_filemode(DB_ENV *, int);
int __log_get_lg_max(DB_ENV *, uint32 *);
int __log_set_lg_max(DB_ENV *, uint32);
int __log_get_lg_regionmax(DB_ENV *, uint32 *);
int __log_set_lg_regionmax(DB_ENV *, uint32);
int __log_get_lg_dir(DB_ENV *, const char **);
int __log_set_lg_dir(DB_ENV *, const char *);
void __log_get_flags(DB_ENV *, uint32 *);
void __log_set_flags(ENV *, uint32, int);
int __log_get_config(DB_ENV *, uint32, int *);
int __log_set_config(DB_ENV *, uint32, int);
int __log_set_config_int(DB_ENV *, uint32, int, int);
int __log_check_sizes(ENV *, uint32, uint32);
int __log_print_record (ENV *, DBT *, DB_LSN *, char *, DB_LOG_RECSPEC *, void *);
int __log_put_pp(DB_ENV *, DB_LSN *, const DBT *, uint32);
int __log_put(ENV *, DB_LSN *, const DBT *, uint32);
int __log_current_lsn_int(ENV *, DB_LSN *, uint32 *, uint32 *);
int __log_current_lsn(ENV *, DB_LSN *, uint32 *, uint32 *);
int __log_newfile(DB_LOG *, DB_LSN *, uint32, uint32);
int __log_flush_pp(DB_ENV *, const DB_LSN *);
int __log_flush(ENV *, const DB_LSN *);
int __log_flush_int(DB_LOG *, const DB_LSN *, int);
int __log_file_pp(DB_ENV *, const DB_LSN *, char *, size_t);
int __log_name(DB_LOG *, uint32, char **, DB_FH **, uint32);
int __log_rep_put(ENV *, DB_LSN *, const DBT *, uint32);
int __log_put_record_pp(DB_ENV *, DB *, DB_TXN *, DB_LSN *, uint32, uint32, uint32, uint32, DB_LOG_RECSPEC *, ...);
int __log_put_record(ENV *, DB *, DB_TXN *, DB_LSN *, uint32, uint32, uint32, uint32, DB_LOG_RECSPEC *, ...);
int __log_stat_pp(DB_ENV *, DB_LOG_STAT **, uint32);
int __log_stat_print_pp(DB_ENV *, uint32);
int __log_stat_print(ENV *, uint32);
int __log_verify_pp(DB_ENV *, const DB_LOG_VERIFY_CONFIG *);
int __log_verify(DB_ENV *, const DB_LOG_VERIFY_CONFIG *, DB_THREAD_INFO *);
int __log_verify_wrap(ENV *, const char *, uint32, const char *, const char *, __time64_t, __time64_t, uint32, uint32, uint32, uint32, int, int);
int __crdel_init_verify(ENV *, DB_DISTAB *);
int __db_init_verify(ENV *, DB_DISTAB *);
int __dbreg_init_verify(ENV *, DB_DISTAB *);
int __bam_init_verify(ENV *, DB_DISTAB *);
int __fop_init_verify(ENV *, DB_DISTAB *);
int __ham_init_verify(ENV *, DB_DISTAB *);
int __heap_init_verify(ENV *, DB_DISTAB *);
int __qam_init_verify(ENV *, DB_DISTAB *);
int __txn_init_verify(ENV *, DB_DISTAB *);
void __db_log_verify_global_report(const DB_LOG_VRFY_INFO *);
int __crdel_metasub_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __crdel_inmem_create_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __crdel_inmem_rename_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __crdel_inmem_remove_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_addrem_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_big_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_ovref_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_relink_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_debug_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_noop_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_alloc_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_alloc_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_free_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_free_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_cksum_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_freedata_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_freedata_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_init_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_sort_44_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pg_trunc_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_realloc_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_relink_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_merge_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __db_pgno_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __dbreg_register_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_split_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_split_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_rsplit_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_adj_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_irep_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_cadjust_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_cdel_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_repl_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_root_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_curadj_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_rcuradj_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_relink_43_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __bam_merge_44_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_create_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_create_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_remove_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_write_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_write_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_rename_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_rename_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __fop_file_remove_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_insdel_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_newpage_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_splitdata_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_replace_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_copypage_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_metagroup_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_metagroup_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_groupalloc_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_groupalloc_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_changeslot_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_contract_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_curadj_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __ham_chgpg_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __heap_addrem_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __heap_pg_alloc_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __heap_trunc_meta_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __heap_trunc_page_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __qam_incfirst_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __qam_mvptr_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __qam_del_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __qam_add_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __qam_delext_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_regop_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_regop_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_ckp_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_ckp_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_child_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_xa_regop_42_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_prepare_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __txn_recycle_verify(ENV *, DBT *, DB_LSN *, db_recops, void *);
int __create_log_vrfy_info(const DB_LOG_VERIFY_CONFIG *, DB_LOG_VRFY_INFO **, DB_THREAD_INFO *);
int __destroy_log_vrfy_info(DB_LOG_VRFY_INFO *);
int __put_txn_vrfy_info(const DB_LOG_VRFY_INFO *, const VRFY_TXN_INFO *);
int __get_txn_vrfy_info(const DB_LOG_VRFY_INFO *, uint32, VRFY_TXN_INFO **);
int __add_recycle_lsn_range(DB_LOG_VRFY_INFO *, const DB_LSN *, uint32, uint32);
int __iterate_txninfo(DB_LOG_VRFY_INFO *, uint32, uint32, TXNINFO_HANDLER, void *);
int __rem_last_recycle_lsn(VRFY_TXN_INFO *);
int __add_file_updated(VRFY_TXN_INFO *, const DBT *, int32);
int __del_file_updated(VRFY_TXN_INFO *, const DBT *);
int __clear_fileups(VRFY_TXN_INFO *);
int __free_txninfo_stack(VRFY_TXN_INFO *);
int __free_txninfo(VRFY_TXN_INFO *);
int __put_filereg_info(const DB_LOG_VRFY_INFO *, const VRFY_FILEREG_INFO *);
int __del_filelife(const DB_LOG_VRFY_INFO *, int32);
int __put_filelife(const DB_LOG_VRFY_INFO *, VRFY_FILELIFE *);
int __get_filelife(const DB_LOG_VRFY_INFO *, int32, VRFY_FILELIFE **);
int __get_filereg_by_dbregid(const DB_LOG_VRFY_INFO *, int32, VRFY_FILEREG_INFO **);
int __add_dbregid(DB_LOG_VRFY_INFO *, VRFY_FILEREG_INFO *, int32, uint32, DB_LSN, DBTYPE, db_pgno_t, int *);
int __get_filereg_info(const DB_LOG_VRFY_INFO *, const DBT *, VRFY_FILEREG_INFO **);
int __free_filereg_info(VRFY_FILEREG_INFO *);
int __get_ckp_info(const DB_LOG_VRFY_INFO *, DB_LSN, VRFY_CKP_INFO **);
int __get_last_ckp_info(const DB_LOG_VRFY_INFO *, VRFY_CKP_INFO **);
int __put_ckp_info(const DB_LOG_VRFY_INFO *, const VRFY_CKP_INFO *);
int __get_timestamp_info(const DB_LOG_VRFY_INFO *, DB_LSN, VRFY_TIMESTAMP_INFO **);
int __get_latest_timestamp_info(const DB_LOG_VRFY_INFO *, DB_LSN, VRFY_TIMESTAMP_INFO **);
int __put_timestamp_info(const DB_LOG_VRFY_INFO *, const VRFY_TIMESTAMP_INFO *);
int __find_lsnrg_by_timerg(DB_LOG_VRFY_INFO *, __time64_t, __time64_t, DB_LSN *, DB_LSN *);
int __add_txnrange(DB_LOG_VRFY_INFO *, uint32, DB_LSN, int32, int);
int __get_aborttxn(DB_LOG_VRFY_INFO *, DB_LSN);
int __txn_started(DB_LOG_VRFY_INFO *, DB_LSN, uint32, int *);
int __set_logvrfy_dbfuid(DB_LOG_VRFY_INFO *);
int __add_page_to_txn(DB_LOG_VRFY_INFO *, int32, db_pgno_t, uint32, uint32 *, int *);
int __del_txn_pages(DB_LOG_VRFY_INFO *, uint32);
int __is_ancestor_txn(DB_LOG_VRFY_INFO *, uint32, uint32, DB_LSN, int *);
int __return_txn_pages(DB_LOG_VRFY_INFO *, uint32, uint32);

#if defined(__cplusplus)
}
#endif
#endif /* !_log_ext_h_ */
