/* vetisamsAMSMercuryG2BBindingProxy.h
   Generated by gSOAP 2.8.8 from vetisams.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef vetisamsAMSMercuryG2BBindingProxy_H
#define vetisamsAMSMercuryG2BBindingProxy_H
#include "vetisamsH.h"

class SOAP_CMAC AMSMercuryG2BBindingProxy : public soap
{ public:
	const char *soap_endpoint; // Endpoint URL of service 'AMSMercuryG2BBindingProxy' (change as needed)
	AMSMercuryG2BBindingProxy(); // Constructor
	AMSMercuryG2BBindingProxy(const struct soap&); // Construct from another engine state
	AMSMercuryG2BBindingProxy(const char *url); // Constructor with endpoint URL
	AMSMercuryG2BBindingProxy(soap_mode iomode); // Constructor with engine input+output mode control
	AMSMercuryG2BBindingProxy(const char *url, soap_mode iomode); // Constructor with URL and input+output mode control
	AMSMercuryG2BBindingProxy(soap_mode imode, soap_mode omode); // Constructor with engine input and output mode control
	virtual	~AMSMercuryG2BBindingProxy(); // Destructor frees deserialized data
	virtual	void AMSMercuryG2BBindingProxy_init(soap_mode imode, soap_mode omode); // Initializer used by constructors
	virtual	void destroy(); // Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void reset(); // Delete all deserialized data and reset to default
	virtual	void soap_noheader(); // Disables and removes SOAP Header from message
	virtual	const SOAP_ENV__Header *soap_header(); // Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault(); // Get SOAP Fault structure (NULL when absent)
	virtual	const char *soap_fault_string(); // Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_detail(); // Get SOAP Fault detail as string (NULL when absent)
	virtual	int soap_close_socket(); // Close connection (normally automatic, except for send_X ops)
	virtual	int soap_force_close_socket(); // Force close connection (can kill a thread blocked on IO)
	virtual	void soap_print_fault(FILE*); // Print fault
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'processIncomingConsignmentRequest' (returns error code or SOAP_OK)
	virtual	int processIncomingConsignmentRequest(g2ba__ProcessIncomingConsignmentRequest *g2ba__processIncomingConsignmentRequest, g2ba__ProcessIncomingConsignmentResponse *g2ba__processIncomingConsignmentResponse) { return processIncomingConsignmentRequest(NULL, NULL, g2ba__processIncomingConsignmentRequest, g2ba__processIncomingConsignmentResponse); }
	virtual	int processIncomingConsignmentRequest(const char *endpoint, const char *soap_action, g2ba__ProcessIncomingConsignmentRequest *g2ba__processIncomingConsignmentRequest, g2ba__ProcessIncomingConsignmentResponse *g2ba__processIncomingConsignmentResponse);

	/// Web service operation 'prepareOutgoingConsignmentRequest' (returns error code or SOAP_OK)
	virtual	int prepareOutgoingConsignmentRequest(g2ba__PrepareOutgoingConsignmentRequest *g2ba__prepareOutgoingConsignmentRequest, g2ba__PrepareOutgoingConsignmentResponse *g2ba__prepareOutgoingConsignmentResponse) { return prepareOutgoingConsignmentRequest(NULL, NULL, g2ba__prepareOutgoingConsignmentRequest, g2ba__prepareOutgoingConsignmentResponse); }
	virtual	int prepareOutgoingConsignmentRequest(const char *endpoint, const char *soap_action, g2ba__PrepareOutgoingConsignmentRequest *g2ba__prepareOutgoingConsignmentRequest, g2ba__PrepareOutgoingConsignmentResponse *g2ba__prepareOutgoingConsignmentResponse);

	/// Web service operation 'registerProductionOperationRequest' (returns error code or SOAP_OK)
	virtual	int registerProductionOperationRequest(g2ba__RegisterProductionOperationRequest *g2ba__registerProductionOperationRequest, g2ba__RegisterProductionOperationResponse *g2ba__registerProductionOperationResponse) { return registerProductionOperationRequest(NULL, NULL, g2ba__registerProductionOperationRequest, g2ba__registerProductionOperationResponse); }
	virtual	int registerProductionOperationRequest(const char *endpoint, const char *soap_action, g2ba__RegisterProductionOperationRequest *g2ba__registerProductionOperationRequest, g2ba__RegisterProductionOperationResponse *g2ba__registerProductionOperationResponse);

	/// Web service operation 'mergeStockEntriesRequest' (returns error code or SOAP_OK)
	virtual	int mergeStockEntriesRequest(g2ba__MergeStockEntriesRequest *g2ba__mergeStockEntriesRequest, g2ba__MergeStockEntriesResponse *g2ba__mergeStockEntriesResponse) { return mergeStockEntriesRequest(NULL, NULL, g2ba__mergeStockEntriesRequest, g2ba__mergeStockEntriesResponse); }
	virtual	int mergeStockEntriesRequest(const char *endpoint, const char *soap_action, g2ba__MergeStockEntriesRequest *g2ba__mergeStockEntriesRequest, g2ba__MergeStockEntriesResponse *g2ba__mergeStockEntriesResponse);

	/// Web service operation 'withdrawVetDocumentRequest' (returns error code or SOAP_OK)
	virtual	int withdrawVetDocumentRequest(g2ba__WithdrawVetDocumentRequest *g2ba__withdrawVetDocumentRequest, g2ba__WithdrawVetDocumentResponse *g2ba__withdrawVetDocumentResponse) { return withdrawVetDocumentRequest(NULL, NULL, g2ba__withdrawVetDocumentRequest, g2ba__withdrawVetDocumentResponse); }
	virtual	int withdrawVetDocumentRequest(const char *endpoint, const char *soap_action, g2ba__WithdrawVetDocumentRequest *g2ba__withdrawVetDocumentRequest, g2ba__WithdrawVetDocumentResponse *g2ba__withdrawVetDocumentResponse);

	/// Web service operation 'modifyBusinessEntityRequest' (returns error code or SOAP_OK)
	virtual	int modifyBusinessEntityRequest(g2ba__ModifyBusinessEntityRequest *g2ba__modifyBusinessEntityRequest, g2ba__ModifyBusinessEntityResponse *g2ba__modifyBusinessEntityResponse) { return modifyBusinessEntityRequest(NULL, NULL, g2ba__modifyBusinessEntityRequest, g2ba__modifyBusinessEntityResponse); }
	virtual	int modifyBusinessEntityRequest(const char *endpoint, const char *soap_action, g2ba__ModifyBusinessEntityRequest *g2ba__modifyBusinessEntityRequest, g2ba__ModifyBusinessEntityResponse *g2ba__modifyBusinessEntityResponse);

	/// Web service operation 'modifyEnterpriseRequest' (returns error code or SOAP_OK)
	virtual	int modifyEnterpriseRequest(g2ba__ModifyEnterpriseRequest *g2ba__modifyEnterpriseRequest, g2ba__ModifyEnterpriseResponse *g2ba__modifyEnterpriseResponse) { return modifyEnterpriseRequest(NULL, NULL, g2ba__modifyEnterpriseRequest, g2ba__modifyEnterpriseResponse); }
	virtual	int modifyEnterpriseRequest(const char *endpoint, const char *soap_action, g2ba__ModifyEnterpriseRequest *g2ba__modifyEnterpriseRequest, g2ba__ModifyEnterpriseResponse *g2ba__modifyEnterpriseResponse);

	/// Web service operation 'modifyActivityLocationsRequest' (returns error code or SOAP_OK)
	virtual	int modifyActivityLocationsRequest(g2ba__ModifyActivityLocationsRequest *g2ba__modifyActivityLocationsRequest, g2ba__ModifyActivityLocationsResponse *g2ba__modifyActivityLocationsResponse) { return modifyActivityLocationsRequest(NULL, NULL, g2ba__modifyActivityLocationsRequest, g2ba__modifyActivityLocationsResponse); }
	virtual	int modifyActivityLocationsRequest(const char *endpoint, const char *soap_action, g2ba__ModifyActivityLocationsRequest *g2ba__modifyActivityLocationsRequest, g2ba__ModifyActivityLocationsResponse *g2ba__modifyActivityLocationsResponse);

	/// Web service operation 'resolveDiscrepancyRequest' (returns error code or SOAP_OK)
	virtual	int resolveDiscrepancyRequest(g2ba__ResolveDiscrepancyRequest *g2ba__resolveDiscrepancyRequest, g2ba__ResolveDiscrepancyResponse *g2ba__resolveDiscrepancyResponse) { return resolveDiscrepancyRequest(NULL, NULL, g2ba__resolveDiscrepancyRequest, g2ba__resolveDiscrepancyResponse); }
	virtual	int resolveDiscrepancyRequest(const char *endpoint, const char *soap_action, g2ba__ResolveDiscrepancyRequest *g2ba__resolveDiscrepancyRequest, g2ba__ResolveDiscrepancyResponse *g2ba__resolveDiscrepancyResponse);

	/// Web service operation 'modifyProducerStockListRequest' (returns error code or SOAP_OK)
	virtual	int modifyProducerStockListRequest(g2ba__ModifyProducerStockListRequest *g2ba__modifyProducerStockListRequest, g2ba__ModifyProducerStockListResponse *g2ba__modifyProducerStockListResponse) { return modifyProducerStockListRequest(NULL, NULL, g2ba__modifyProducerStockListRequest, g2ba__modifyProducerStockListResponse); }
	virtual	int modifyProducerStockListRequest(const char *endpoint, const char *soap_action, g2ba__ModifyProducerStockListRequest *g2ba__modifyProducerStockListRequest, g2ba__ModifyProducerStockListResponse *g2ba__modifyProducerStockListResponse);

	/// Web service operation 'getVetDocumentByUuidRequest' (returns error code or SOAP_OK)
	virtual	int getVetDocumentByUuidRequest(g2ba__GetVetDocumentByUuidRequest *g2ba__getVetDocumentByUuidRequest, g2ba__GetVetDocumentByUuidResponse *g2ba__getVetDocumentByUuidResponse) { return getVetDocumentByUuidRequest(NULL, NULL, g2ba__getVetDocumentByUuidRequest, g2ba__getVetDocumentByUuidResponse); }
	virtual	int getVetDocumentByUuidRequest(const char *endpoint, const char *soap_action, g2ba__GetVetDocumentByUuidRequest *g2ba__getVetDocumentByUuidRequest, g2ba__GetVetDocumentByUuidResponse *g2ba__getVetDocumentByUuidResponse);

	/// Web service operation 'getVetDocumentListRequest' (returns error code or SOAP_OK)
	virtual	int getVetDocumentListRequest(g2ba__GetVetDocumentListRequest *g2ba__getVetDocumentListRequest, g2ba__GetVetDocumentListResponse *g2ba__getVetDocumentListResponse) { return getVetDocumentListRequest(NULL, NULL, g2ba__getVetDocumentListRequest, g2ba__getVetDocumentListResponse); }
	virtual	int getVetDocumentListRequest(const char *endpoint, const char *soap_action, g2ba__GetVetDocumentListRequest *g2ba__getVetDocumentListRequest, g2ba__GetVetDocumentListResponse *g2ba__getVetDocumentListResponse);

	/// Web service operation 'getVetDocumentChangesListRequest' (returns error code or SOAP_OK)
	virtual	int getVetDocumentChangesListRequest(g2ba__GetVetDocumentChangesListRequest *g2ba__getVetDocumentChangesListRequest, g2ba__GetVetDocumentChangesListResponse *g2ba__getVetDocumentChangesListResponse) { return getVetDocumentChangesListRequest(NULL, NULL, g2ba__getVetDocumentChangesListRequest, g2ba__getVetDocumentChangesListResponse); }
	virtual	int getVetDocumentChangesListRequest(const char *endpoint, const char *soap_action, g2ba__GetVetDocumentChangesListRequest *g2ba__getVetDocumentChangesListRequest, g2ba__GetVetDocumentChangesListResponse *g2ba__getVetDocumentChangesListResponse);

	/// Web service operation 'getStockEntryByGuidRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryByGuidRequest(g2ba__GetStockEntryByGuidRequest *g2ba__getStockEntryByGuidRequest, g2ba__GetStockEntryByGuidResponse *g2ba__getStockEntryByGuidResponse) { return getStockEntryByGuidRequest(NULL, NULL, g2ba__getStockEntryByGuidRequest, g2ba__getStockEntryByGuidResponse); }
	virtual	int getStockEntryByGuidRequest(const char *endpoint, const char *soap_action, g2ba__GetStockEntryByGuidRequest *g2ba__getStockEntryByGuidRequest, g2ba__GetStockEntryByGuidResponse *g2ba__getStockEntryByGuidResponse);

	/// Web service operation 'getStockEntryByUuidRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryByUuidRequest(g2ba__GetStockEntryByUuidRequest *g2ba__getStockEntryByUuidRequest, g2ba__GetStockEntryByUuidResponse *g2ba__getStockEntryByUuidResponse) { return getStockEntryByUuidRequest(NULL, NULL, g2ba__getStockEntryByUuidRequest, g2ba__getStockEntryByUuidResponse); }
	virtual	int getStockEntryByUuidRequest(const char *endpoint, const char *soap_action, g2ba__GetStockEntryByUuidRequest *g2ba__getStockEntryByUuidRequest, g2ba__GetStockEntryByUuidResponse *g2ba__getStockEntryByUuidResponse);

	/// Web service operation 'getStockEntryListRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryListRequest(g2ba__GetStockEntryListRequest *g2ba__getStockEntryListRequest, g2ba__GetStockEntryListResponse *g2ba__getStockEntryListResponse) { return getStockEntryListRequest(NULL, NULL, g2ba__getStockEntryListRequest, g2ba__getStockEntryListResponse); }
	virtual	int getStockEntryListRequest(const char *endpoint, const char *soap_action, g2ba__GetStockEntryListRequest *g2ba__getStockEntryListRequest, g2ba__GetStockEntryListResponse *g2ba__getStockEntryListResponse);

	/// Web service operation 'getStockEntryChangesListRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryChangesListRequest(g2ba__GetStockEntryChangesListRequest *g2ba__getStockEntryChangesListRequest, g2ba__GetStockEntryChangesListResponse *g2ba__getStockEntryChangesListResponse) { return getStockEntryChangesListRequest(NULL, NULL, g2ba__getStockEntryChangesListRequest, g2ba__getStockEntryChangesListResponse); }
	virtual	int getStockEntryChangesListRequest(const char *endpoint, const char *soap_action, g2ba__GetStockEntryChangesListRequest *g2ba__getStockEntryChangesListRequest, g2ba__GetStockEntryChangesListResponse *g2ba__getStockEntryChangesListResponse);

	/// Web service operation 'getStockEntryVersionListRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryVersionListRequest(g2ba__GetStockEntryVersionListRequest *g2ba__getStockEntryVersionListRequest, g2ba__GetStockEntryVersionListResponse *g2ba__getStockEntryVersionListResponse) { return getStockEntryVersionListRequest(NULL, NULL, g2ba__getStockEntryVersionListRequest, g2ba__getStockEntryVersionListResponse); }
	virtual	int getStockEntryVersionListRequest(const char *endpoint, const char *soap_action, g2ba__GetStockEntryVersionListRequest *g2ba__getStockEntryVersionListRequest, g2ba__GetStockEntryVersionListResponse *g2ba__getStockEntryVersionListResponse);

	/// Web service operation 'updateTransportMovementDetailsRequest' (returns error code or SOAP_OK)
	virtual	int updateTransportMovementDetailsRequest(g2ba__UpdateTransportMovementDetailsRequest *g2ba__updateTransportMovementDetailsRequest, g2ba__UpdateTransportMovementDetailsResponse *g2ba__updateTransportMovementDetailsResponse) { return updateTransportMovementDetailsRequest(NULL, NULL, g2ba__updateTransportMovementDetailsRequest, g2ba__updateTransportMovementDetailsResponse); }
	virtual	int updateTransportMovementDetailsRequest(const char *endpoint, const char *soap_action, g2ba__UpdateTransportMovementDetailsRequest *g2ba__updateTransportMovementDetailsRequest, g2ba__UpdateTransportMovementDetailsResponse *g2ba__updateTransportMovementDetailsResponse);

	/// Web service operation 'updateVeterinaryEventsRequest' (returns error code or SOAP_OK)
	virtual	int updateVeterinaryEventsRequest(g2ba__UpdateVeterinaryEventsRequest *g2ba__updateVeterinaryEventsRequest, g2ba__UpdateVeterinaryEventsResponse *g2ba__updateVeterinaryEventsResponse) { return updateVeterinaryEventsRequest(NULL, NULL, g2ba__updateVeterinaryEventsRequest, g2ba__updateVeterinaryEventsResponse); }
	virtual	int updateVeterinaryEventsRequest(const char *endpoint, const char *soap_action, g2ba__UpdateVeterinaryEventsRequest *g2ba__updateVeterinaryEventsRequest, g2ba__UpdateVeterinaryEventsResponse *g2ba__updateVeterinaryEventsResponse);

	/// Web service operation 'checkShipmentRegionalizationRequest' (returns error code or SOAP_OK)
	virtual	int checkShipmentRegionalizationRequest(g2ba__CheckShipmentRegionalizationRequest *g2ba__checkShipmentRegionalizationRequest, g2ba__CheckShipmentRegionalizationResponse *g2ba__checkShipmentRegionalizationResponse) { return checkShipmentRegionalizationRequest(NULL, NULL, g2ba__checkShipmentRegionalizationRequest, g2ba__checkShipmentRegionalizationResponse); }
	virtual	int checkShipmentRegionalizationRequest(const char *endpoint, const char *soap_action, g2ba__CheckShipmentRegionalizationRequest *g2ba__checkShipmentRegionalizationRequest, g2ba__CheckShipmentRegionalizationResponse *g2ba__checkShipmentRegionalizationResponse);

	/// Web service operation 'addBusinessEntityUserRequest' (returns error code or SOAP_OK)
	virtual	int addBusinessEntityUserRequest(g2ba__AddBusinessEntityUserRequest *g2ba__addBusinessEntityUserRequest, g2ba__AddBusinessEntityUserResponse *g2ba__addBusinessEntityUserResponse) { return addBusinessEntityUserRequest(NULL, NULL, g2ba__addBusinessEntityUserRequest, g2ba__addBusinessEntityUserResponse); }
	virtual	int addBusinessEntityUserRequest(const char *endpoint, const char *soap_action, g2ba__AddBusinessEntityUserRequest *g2ba__addBusinessEntityUserRequest, g2ba__AddBusinessEntityUserResponse *g2ba__addBusinessEntityUserResponse);

	/// Web service operation 'getBusinessEntityUserListRequest' (returns error code or SOAP_OK)
	virtual	int getBusinessEntityUserListRequest(g2ba__GetBusinessEntityUserListRequest *g2ba__getBusinessEntityUserListRequest, g2ba__GetBusinessEntityUserListResponse *g2ba__getBusinessEntityUserListResponse) { return getBusinessEntityUserListRequest(NULL, NULL, g2ba__getBusinessEntityUserListRequest, g2ba__getBusinessEntityUserListResponse); }
	virtual	int getBusinessEntityUserListRequest(const char *endpoint, const char *soap_action, g2ba__GetBusinessEntityUserListRequest *g2ba__getBusinessEntityUserListRequest, g2ba__GetBusinessEntityUserListResponse *g2ba__getBusinessEntityUserListResponse);

	/// Web service operation 'getBusinessEntityUserRequest' (returns error code or SOAP_OK)
	virtual	int getBusinessEntityUserRequest(g2ba__GetBusinessEntityUserRequest *g2ba__getBusinessEntityUserRequest, g2ba__GetBusinessEntityUserResponse *g2ba__getBusinessEntityUserResponse) { return getBusinessEntityUserRequest(NULL, NULL, g2ba__getBusinessEntityUserRequest, g2ba__getBusinessEntityUserResponse); }
	virtual	int getBusinessEntityUserRequest(const char *endpoint, const char *soap_action, g2ba__GetBusinessEntityUserRequest *g2ba__getBusinessEntityUserRequest, g2ba__GetBusinessEntityUserResponse *g2ba__getBusinessEntityUserResponse);

	/// Web service operation 'updateUserAuthoritiesRequest' (returns error code or SOAP_OK)
	virtual	int updateUserAuthoritiesRequest(g2ba__UpdateUserAuthoritiesRequest *g2ba__updateUserAuthoritiesRequest, g2ba__UpdateUserAuthoritiesResponse *g2ba__updateUserAuthoritiesResponse) { return updateUserAuthoritiesRequest(NULL, NULL, g2ba__updateUserAuthoritiesRequest, g2ba__updateUserAuthoritiesResponse); }
	virtual	int updateUserAuthoritiesRequest(const char *endpoint, const char *soap_action, g2ba__UpdateUserAuthoritiesRequest *g2ba__updateUserAuthoritiesRequest, g2ba__UpdateUserAuthoritiesResponse *g2ba__updateUserAuthoritiesResponse);

	/// Web service operation 'updateUserWorkingAreasRequest' (returns error code or SOAP_OK)
	virtual	int updateUserWorkingAreasRequest(g2ba__UpdateUserWorkingAreasRequest *g2ba__updateUserWorkingAreasRequest, g2ba__UpdateUserWorkingAreasResponse *g2ba__updateUserWorkingAreasResponse) { return updateUserWorkingAreasRequest(NULL, NULL, g2ba__updateUserWorkingAreasRequest, g2ba__updateUserWorkingAreasResponse); }
	virtual	int updateUserWorkingAreasRequest(const char *endpoint, const char *soap_action, g2ba__UpdateUserWorkingAreasRequest *g2ba__updateUserWorkingAreasRequest, g2ba__UpdateUserWorkingAreasResponse *g2ba__updateUserWorkingAreasResponse);

	/// Web service operation 'unbindBusinessEntityUserRequest' (returns error code or SOAP_OK)
	virtual	int unbindBusinessEntityUserRequest(g2ba__UnbindBusinessEntityUserRequest *g2ba__unbindBusinessEntityUserRequest, g2ba__UnbindBusinessEntityUserResponse *g2ba__unbindBusinessEntityUserResponse) { return unbindBusinessEntityUserRequest(NULL, NULL, g2ba__unbindBusinessEntityUserRequest, g2ba__unbindBusinessEntityUserResponse); }
	virtual	int unbindBusinessEntityUserRequest(const char *endpoint, const char *soap_action, g2ba__UnbindBusinessEntityUserRequest *g2ba__unbindBusinessEntityUserRequest, g2ba__UnbindBusinessEntityUserResponse *g2ba__unbindBusinessEntityUserResponse);

	/// Web service operation 'getApplicableUserAuthorityListRequest' (returns error code or SOAP_OK)
	virtual	int getApplicableUserAuthorityListRequest(g2ba__GetApplicableUserAuthorityListRequest *g2ba__getApplicableUserAuthorityListRequest, g2ba__GetApplicableUserAuthorityListResponse *g2ba__getApplicableUserAuthorityListResponse) { return getApplicableUserAuthorityListRequest(NULL, NULL, g2ba__getApplicableUserAuthorityListRequest, g2ba__getApplicableUserAuthorityListResponse); }
	virtual	int getApplicableUserAuthorityListRequest(const char *endpoint, const char *soap_action, g2ba__GetApplicableUserAuthorityListRequest *g2ba__getApplicableUserAuthorityListRequest, g2ba__GetApplicableUserAuthorityListResponse *g2ba__getApplicableUserAuthorityListResponse);
};
#endif
