/* vetisamsAMSMercuryG2BBindingProxy.h
   Generated by gSOAP 2.8.8 from vetisams.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef vetisamsAMSMercuryG2BBindingProxy_H
#define vetisamsAMSMercuryG2BBindingProxy_H
#include "vetisamsH.h"

class SOAP_CMAC AMSMercuryG2BBindingProxy : public soap
{ public:
	const char *soap_endpoint; // Endpoint URL of service 'AMSMercuryG2BBindingProxy' (change as needed)
	AMSMercuryG2BBindingProxy(); // Constructor
	AMSMercuryG2BBindingProxy(const struct soap&); // Construct from another engine state
	AMSMercuryG2BBindingProxy(const char *url); // Constructor with endpoint URL
	AMSMercuryG2BBindingProxy(soap_mode iomode); // Constructor with engine input+output mode control
	AMSMercuryG2BBindingProxy(const char *url, soap_mode iomode); // Constructor with URL and input+output mode control
	AMSMercuryG2BBindingProxy(soap_mode imode, soap_mode omode); // Constructor with engine input and output mode control
	virtual	~AMSMercuryG2BBindingProxy(); // Destructor frees deserialized data
	virtual	void AMSMercuryG2BBindingProxy_init(soap_mode imode, soap_mode omode); // Initializer used by constructors
	virtual	void destroy(); // Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void reset(); // Delete all deserialized data and reset to default
	virtual	void soap_noheader(); // Disables and removes SOAP Header from message
	virtual	const SOAP_ENV__Header *soap_header(); // Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault(); // Get SOAP Fault structure (NULL when absent)
	virtual	const char *soap_fault_string(); // Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_detail(); // Get SOAP Fault detail as string (NULL when absent)
	virtual	int soap_close_socket(); // Close connection (normally automatic, except for send_X ops)
	virtual	int soap_force_close_socket(); // Force close connection (can kill a thread blocked on IO)
	virtual	void soap_print_fault(FILE*); // Print fault
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'processIncomingConsignmentRequest' (returns error code or SOAP_OK)
	virtual	int processIncomingConsignmentRequest(ns5__ProcessIncomingConsignmentRequest *ns5__processIncomingConsignmentRequest, ns5__ProcessIncomingConsignmentResponse *ns5__processIncomingConsignmentResponse) { return processIncomingConsignmentRequest(NULL, NULL, ns5__processIncomingConsignmentRequest, ns5__processIncomingConsignmentResponse); }
	virtual	int processIncomingConsignmentRequest(const char *endpoint, const char *soap_action, ns5__ProcessIncomingConsignmentRequest *ns5__processIncomingConsignmentRequest, ns5__ProcessIncomingConsignmentResponse *ns5__processIncomingConsignmentResponse);

	/// Web service operation 'prepareOutgoingConsignmentRequest' (returns error code or SOAP_OK)
	virtual	int prepareOutgoingConsignmentRequest(ns5__PrepareOutgoingConsignmentRequest *ns5__prepareOutgoingConsignmentRequest, ns5__PrepareOutgoingConsignmentResponse *ns5__prepareOutgoingConsignmentResponse) { return prepareOutgoingConsignmentRequest(NULL, NULL, ns5__prepareOutgoingConsignmentRequest, ns5__prepareOutgoingConsignmentResponse); }
	virtual	int prepareOutgoingConsignmentRequest(const char *endpoint, const char *soap_action, ns5__PrepareOutgoingConsignmentRequest *ns5__prepareOutgoingConsignmentRequest, ns5__PrepareOutgoingConsignmentResponse *ns5__prepareOutgoingConsignmentResponse);

	/// Web service operation 'registerProductionOperationRequest' (returns error code or SOAP_OK)
	virtual	int registerProductionOperationRequest(ns5__RegisterProductionOperationRequest *ns5__registerProductionOperationRequest, ns5__RegisterProductionOperationResponse *ns5__registerProductionOperationResponse) { return registerProductionOperationRequest(NULL, NULL, ns5__registerProductionOperationRequest, ns5__registerProductionOperationResponse); }
	virtual	int registerProductionOperationRequest(const char *endpoint, const char *soap_action, ns5__RegisterProductionOperationRequest *ns5__registerProductionOperationRequest, ns5__RegisterProductionOperationResponse *ns5__registerProductionOperationResponse);

	/// Web service operation 'mergeStockEntriesRequest' (returns error code or SOAP_OK)
	virtual	int mergeStockEntriesRequest(ns5__MergeStockEntriesRequest *ns5__mergeStockEntriesRequest, ns5__MergeStockEntriesResponse *ns5__mergeStockEntriesResponse) { return mergeStockEntriesRequest(NULL, NULL, ns5__mergeStockEntriesRequest, ns5__mergeStockEntriesResponse); }
	virtual	int mergeStockEntriesRequest(const char *endpoint, const char *soap_action, ns5__MergeStockEntriesRequest *ns5__mergeStockEntriesRequest, ns5__MergeStockEntriesResponse *ns5__mergeStockEntriesResponse);

	/// Web service operation 'withdrawVetDocumentRequest' (returns error code or SOAP_OK)
	virtual	int withdrawVetDocumentRequest(ns5__WithdrawVetDocumentRequest *ns5__withdrawVetDocumentRequest, ns5__WithdrawVetDocumentResponse *ns5__withdrawVetDocumentResponse) { return withdrawVetDocumentRequest(NULL, NULL, ns5__withdrawVetDocumentRequest, ns5__withdrawVetDocumentResponse); }
	virtual	int withdrawVetDocumentRequest(const char *endpoint, const char *soap_action, ns5__WithdrawVetDocumentRequest *ns5__withdrawVetDocumentRequest, ns5__WithdrawVetDocumentResponse *ns5__withdrawVetDocumentResponse);

	/// Web service operation 'modifyBusinessEntityRequest' (returns error code or SOAP_OK)
	virtual	int modifyBusinessEntityRequest(ns5__ModifyBusinessEntityRequest *ns5__modifyBusinessEntityRequest, ns5__ModifyBusinessEntityResponse *ns5__modifyBusinessEntityResponse) { return modifyBusinessEntityRequest(NULL, NULL, ns5__modifyBusinessEntityRequest, ns5__modifyBusinessEntityResponse); }
	virtual	int modifyBusinessEntityRequest(const char *endpoint, const char *soap_action, ns5__ModifyBusinessEntityRequest *ns5__modifyBusinessEntityRequest, ns5__ModifyBusinessEntityResponse *ns5__modifyBusinessEntityResponse);

	/// Web service operation 'modifyEnterpriseRequest' (returns error code or SOAP_OK)
	virtual	int modifyEnterpriseRequest(ns5__ModifyEnterpriseRequest *ns5__modifyEnterpriseRequest, ns5__ModifyEnterpriseResponse *ns5__modifyEnterpriseResponse) { return modifyEnterpriseRequest(NULL, NULL, ns5__modifyEnterpriseRequest, ns5__modifyEnterpriseResponse); }
	virtual	int modifyEnterpriseRequest(const char *endpoint, const char *soap_action, ns5__ModifyEnterpriseRequest *ns5__modifyEnterpriseRequest, ns5__ModifyEnterpriseResponse *ns5__modifyEnterpriseResponse);

	/// Web service operation 'modifyActivityLocationsRequest' (returns error code or SOAP_OK)
	virtual	int modifyActivityLocationsRequest(ns5__ModifyActivityLocationsRequest *ns5__modifyActivityLocationsRequest, ns5__ModifyActivityLocationsResponse *ns5__modifyActivityLocationsResponse) { return modifyActivityLocationsRequest(NULL, NULL, ns5__modifyActivityLocationsRequest, ns5__modifyActivityLocationsResponse); }
	virtual	int modifyActivityLocationsRequest(const char *endpoint, const char *soap_action, ns5__ModifyActivityLocationsRequest *ns5__modifyActivityLocationsRequest, ns5__ModifyActivityLocationsResponse *ns5__modifyActivityLocationsResponse);

	/// Web service operation 'resolveDiscrepancyRequest' (returns error code or SOAP_OK)
	virtual	int resolveDiscrepancyRequest(ns5__ResolveDiscrepancyRequest *ns5__resolveDiscrepancyRequest, ns5__ResolveDiscrepancyResponse *ns5__resolveDiscrepancyResponse) { return resolveDiscrepancyRequest(NULL, NULL, ns5__resolveDiscrepancyRequest, ns5__resolveDiscrepancyResponse); }
	virtual	int resolveDiscrepancyRequest(const char *endpoint, const char *soap_action, ns5__ResolveDiscrepancyRequest *ns5__resolveDiscrepancyRequest, ns5__ResolveDiscrepancyResponse *ns5__resolveDiscrepancyResponse);

	/// Web service operation 'modifyProducerStockListRequest' (returns error code or SOAP_OK)
	virtual	int modifyProducerStockListRequest(ns5__ModifyProducerStockListRequest *ns5__modifyProducerStockListRequest, ns5__ModifyProducerStockListResponse *ns5__modifyProducerStockListResponse) { return modifyProducerStockListRequest(NULL, NULL, ns5__modifyProducerStockListRequest, ns5__modifyProducerStockListResponse); }
	virtual	int modifyProducerStockListRequest(const char *endpoint, const char *soap_action, ns5__ModifyProducerStockListRequest *ns5__modifyProducerStockListRequest, ns5__ModifyProducerStockListResponse *ns5__modifyProducerStockListResponse);

	/// Web service operation 'getVetDocumentByUuidRequest' (returns error code or SOAP_OK)
	virtual	int getVetDocumentByUuidRequest(ns5__GetVetDocumentByUuidRequest *ns5__getVetDocumentByUuidRequest, ns5__GetVetDocumentByUuidResponse *ns5__getVetDocumentByUuidResponse) { return getVetDocumentByUuidRequest(NULL, NULL, ns5__getVetDocumentByUuidRequest, ns5__getVetDocumentByUuidResponse); }
	virtual	int getVetDocumentByUuidRequest(const char *endpoint, const char *soap_action, ns5__GetVetDocumentByUuidRequest *ns5__getVetDocumentByUuidRequest, ns5__GetVetDocumentByUuidResponse *ns5__getVetDocumentByUuidResponse);

	/// Web service operation 'getVetDocumentListRequest' (returns error code or SOAP_OK)
	virtual	int getVetDocumentListRequest(ns5__GetVetDocumentListRequest *ns5__getVetDocumentListRequest, ns5__GetVetDocumentListResponse *ns5__getVetDocumentListResponse) { return getVetDocumentListRequest(NULL, NULL, ns5__getVetDocumentListRequest, ns5__getVetDocumentListResponse); }
	virtual	int getVetDocumentListRequest(const char *endpoint, const char *soap_action, ns5__GetVetDocumentListRequest *ns5__getVetDocumentListRequest, ns5__GetVetDocumentListResponse *ns5__getVetDocumentListResponse);

	/// Web service operation 'getVetDocumentChangesListRequest' (returns error code or SOAP_OK)
	virtual	int getVetDocumentChangesListRequest(ns5__GetVetDocumentChangesListRequest *ns5__getVetDocumentChangesListRequest, ns5__GetVetDocumentChangesListResponse *ns5__getVetDocumentChangesListResponse) { return getVetDocumentChangesListRequest(NULL, NULL, ns5__getVetDocumentChangesListRequest, ns5__getVetDocumentChangesListResponse); }
	virtual	int getVetDocumentChangesListRequest(const char *endpoint, const char *soap_action, ns5__GetVetDocumentChangesListRequest *ns5__getVetDocumentChangesListRequest, ns5__GetVetDocumentChangesListResponse *ns5__getVetDocumentChangesListResponse);

	/// Web service operation 'getStockEntryByGuidRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryByGuidRequest(ns5__GetStockEntryByGuidRequest *ns5__getStockEntryByGuidRequest, ns5__GetStockEntryByGuidResponse *ns5__getStockEntryByGuidResponse) { return getStockEntryByGuidRequest(NULL, NULL, ns5__getStockEntryByGuidRequest, ns5__getStockEntryByGuidResponse); }
	virtual	int getStockEntryByGuidRequest(const char *endpoint, const char *soap_action, ns5__GetStockEntryByGuidRequest *ns5__getStockEntryByGuidRequest, ns5__GetStockEntryByGuidResponse *ns5__getStockEntryByGuidResponse);

	/// Web service operation 'getStockEntryByUuidRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryByUuidRequest(ns5__GetStockEntryByUuidRequest *ns5__getStockEntryByUuidRequest, ns5__GetStockEntryByUuidResponse *ns5__getStockEntryByUuidResponse) { return getStockEntryByUuidRequest(NULL, NULL, ns5__getStockEntryByUuidRequest, ns5__getStockEntryByUuidResponse); }
	virtual	int getStockEntryByUuidRequest(const char *endpoint, const char *soap_action, ns5__GetStockEntryByUuidRequest *ns5__getStockEntryByUuidRequest, ns5__GetStockEntryByUuidResponse *ns5__getStockEntryByUuidResponse);

	/// Web service operation 'getStockEntryListRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryListRequest(ns5__GetStockEntryListRequest *ns5__getStockEntryListRequest, ns5__GetStockEntryListResponse *ns5__getStockEntryListResponse) { return getStockEntryListRequest(NULL, NULL, ns5__getStockEntryListRequest, ns5__getStockEntryListResponse); }
	virtual	int getStockEntryListRequest(const char *endpoint, const char *soap_action, ns5__GetStockEntryListRequest *ns5__getStockEntryListRequest, ns5__GetStockEntryListResponse *ns5__getStockEntryListResponse);

	/// Web service operation 'getStockEntryChangesListRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryChangesListRequest(ns5__GetStockEntryChangesListRequest *ns5__getStockEntryChangesListRequest, ns5__GetStockEntryChangesListResponse *ns5__getStockEntryChangesListResponse) { return getStockEntryChangesListRequest(NULL, NULL, ns5__getStockEntryChangesListRequest, ns5__getStockEntryChangesListResponse); }
	virtual	int getStockEntryChangesListRequest(const char *endpoint, const char *soap_action, ns5__GetStockEntryChangesListRequest *ns5__getStockEntryChangesListRequest, ns5__GetStockEntryChangesListResponse *ns5__getStockEntryChangesListResponse);

	/// Web service operation 'getStockEntryVersionListRequest' (returns error code or SOAP_OK)
	virtual	int getStockEntryVersionListRequest(ns5__GetStockEntryVersionListRequest *ns5__getStockEntryVersionListRequest, ns5__GetStockEntryVersionListResponse *ns5__getStockEntryVersionListResponse) { return getStockEntryVersionListRequest(NULL, NULL, ns5__getStockEntryVersionListRequest, ns5__getStockEntryVersionListResponse); }
	virtual	int getStockEntryVersionListRequest(const char *endpoint, const char *soap_action, ns5__GetStockEntryVersionListRequest *ns5__getStockEntryVersionListRequest, ns5__GetStockEntryVersionListResponse *ns5__getStockEntryVersionListResponse);

	/// Web service operation 'updateTransportMovementDetailsRequest' (returns error code or SOAP_OK)
	virtual	int updateTransportMovementDetailsRequest(ns5__UpdateTransportMovementDetailsRequest *ns5__updateTransportMovementDetailsRequest, ns5__UpdateTransportMovementDetailsResponse *ns5__updateTransportMovementDetailsResponse) { return updateTransportMovementDetailsRequest(NULL, NULL, ns5__updateTransportMovementDetailsRequest, ns5__updateTransportMovementDetailsResponse); }
	virtual	int updateTransportMovementDetailsRequest(const char *endpoint, const char *soap_action, ns5__UpdateTransportMovementDetailsRequest *ns5__updateTransportMovementDetailsRequest, ns5__UpdateTransportMovementDetailsResponse *ns5__updateTransportMovementDetailsResponse);

	/// Web service operation 'updateVeterinaryEventsRequest' (returns error code or SOAP_OK)
	virtual	int updateVeterinaryEventsRequest(ns5__UpdateVeterinaryEventsRequest *ns5__updateVeterinaryEventsRequest, ns5__UpdateVeterinaryEventsResponse *ns5__updateVeterinaryEventsResponse) { return updateVeterinaryEventsRequest(NULL, NULL, ns5__updateVeterinaryEventsRequest, ns5__updateVeterinaryEventsResponse); }
	virtual	int updateVeterinaryEventsRequest(const char *endpoint, const char *soap_action, ns5__UpdateVeterinaryEventsRequest *ns5__updateVeterinaryEventsRequest, ns5__UpdateVeterinaryEventsResponse *ns5__updateVeterinaryEventsResponse);

	/// Web service operation 'checkShipmentRegionalizationRequest' (returns error code or SOAP_OK)
	virtual	int checkShipmentRegionalizationRequest(ns5__CheckShipmentRegionalizationRequest *ns5__checkShipmentRegionalizationRequest, ns5__CheckShipmentRegionalizationResponse *ns5__checkShipmentRegionalizationResponse) { return checkShipmentRegionalizationRequest(NULL, NULL, ns5__checkShipmentRegionalizationRequest, ns5__checkShipmentRegionalizationResponse); }
	virtual	int checkShipmentRegionalizationRequest(const char *endpoint, const char *soap_action, ns5__CheckShipmentRegionalizationRequest *ns5__checkShipmentRegionalizationRequest, ns5__CheckShipmentRegionalizationResponse *ns5__checkShipmentRegionalizationResponse);

	/// Web service operation 'addBusinessEntityUserRequest' (returns error code or SOAP_OK)
	virtual	int addBusinessEntityUserRequest(ns5__AddBusinessEntityUserRequest *ns5__addBusinessEntityUserRequest, ns5__AddBusinessEntityUserResponse *ns5__addBusinessEntityUserResponse) { return addBusinessEntityUserRequest(NULL, NULL, ns5__addBusinessEntityUserRequest, ns5__addBusinessEntityUserResponse); }
	virtual	int addBusinessEntityUserRequest(const char *endpoint, const char *soap_action, ns5__AddBusinessEntityUserRequest *ns5__addBusinessEntityUserRequest, ns5__AddBusinessEntityUserResponse *ns5__addBusinessEntityUserResponse);

	/// Web service operation 'getBusinessEntityUserListRequest' (returns error code or SOAP_OK)
	virtual	int getBusinessEntityUserListRequest(ns5__GetBusinessEntityUserListRequest *ns5__getBusinessEntityUserListRequest, ns5__GetBusinessEntityUserListResponse *ns5__getBusinessEntityUserListResponse) { return getBusinessEntityUserListRequest(NULL, NULL, ns5__getBusinessEntityUserListRequest, ns5__getBusinessEntityUserListResponse); }
	virtual	int getBusinessEntityUserListRequest(const char *endpoint, const char *soap_action, ns5__GetBusinessEntityUserListRequest *ns5__getBusinessEntityUserListRequest, ns5__GetBusinessEntityUserListResponse *ns5__getBusinessEntityUserListResponse);

	/// Web service operation 'getBusinessEntityUserRequest' (returns error code or SOAP_OK)
	virtual	int getBusinessEntityUserRequest(ns5__GetBusinessEntityUserRequest *ns5__getBusinessEntityUserRequest, ns5__GetBusinessEntityUserResponse *ns5__getBusinessEntityUserResponse) { return getBusinessEntityUserRequest(NULL, NULL, ns5__getBusinessEntityUserRequest, ns5__getBusinessEntityUserResponse); }
	virtual	int getBusinessEntityUserRequest(const char *endpoint, const char *soap_action, ns5__GetBusinessEntityUserRequest *ns5__getBusinessEntityUserRequest, ns5__GetBusinessEntityUserResponse *ns5__getBusinessEntityUserResponse);

	/// Web service operation 'updateUserAuthoritiesRequest' (returns error code or SOAP_OK)
	virtual	int updateUserAuthoritiesRequest(ns5__UpdateUserAuthoritiesRequest *ns5__updateUserAuthoritiesRequest, ns5__UpdateUserAuthoritiesResponse *ns5__updateUserAuthoritiesResponse) { return updateUserAuthoritiesRequest(NULL, NULL, ns5__updateUserAuthoritiesRequest, ns5__updateUserAuthoritiesResponse); }
	virtual	int updateUserAuthoritiesRequest(const char *endpoint, const char *soap_action, ns5__UpdateUserAuthoritiesRequest *ns5__updateUserAuthoritiesRequest, ns5__UpdateUserAuthoritiesResponse *ns5__updateUserAuthoritiesResponse);

	/// Web service operation 'updateUserWorkingAreasRequest' (returns error code or SOAP_OK)
	virtual	int updateUserWorkingAreasRequest(ns5__UpdateUserWorkingAreasRequest *ns5__updateUserWorkingAreasRequest, ns5__UpdateUserWorkingAreasResponse *ns5__updateUserWorkingAreasResponse) { return updateUserWorkingAreasRequest(NULL, NULL, ns5__updateUserWorkingAreasRequest, ns5__updateUserWorkingAreasResponse); }
	virtual	int updateUserWorkingAreasRequest(const char *endpoint, const char *soap_action, ns5__UpdateUserWorkingAreasRequest *ns5__updateUserWorkingAreasRequest, ns5__UpdateUserWorkingAreasResponse *ns5__updateUserWorkingAreasResponse);

	/// Web service operation 'unbindBusinessEntityUserRequest' (returns error code or SOAP_OK)
	virtual	int unbindBusinessEntityUserRequest(ns5__UnbindBusinessEntityUserRequest *ns5__unbindBusinessEntityUserRequest, ns5__UnbindBusinessEntityUserResponse *ns5__unbindBusinessEntityUserResponse) { return unbindBusinessEntityUserRequest(NULL, NULL, ns5__unbindBusinessEntityUserRequest, ns5__unbindBusinessEntityUserResponse); }
	virtual	int unbindBusinessEntityUserRequest(const char *endpoint, const char *soap_action, ns5__UnbindBusinessEntityUserRequest *ns5__unbindBusinessEntityUserRequest, ns5__UnbindBusinessEntityUserResponse *ns5__unbindBusinessEntityUserResponse);

	/// Web service operation 'getAppliedUserAuthorityListRequest' (returns error code or SOAP_OK)
	virtual	int getAppliedUserAuthorityListRequest(ns5__GetAppliedUserAuthorityListRequest *ns5__getAppliedUserAuthorityListRequest, ns5__GetAppliedUserAuthorityListResponse *ns5__getAppliedUserAuthorityListResponse) { return getAppliedUserAuthorityListRequest(NULL, NULL, ns5__getAppliedUserAuthorityListRequest, ns5__getAppliedUserAuthorityListResponse); }
	virtual	int getAppliedUserAuthorityListRequest(const char *endpoint, const char *soap_action, ns5__GetAppliedUserAuthorityListRequest *ns5__getAppliedUserAuthorityListRequest, ns5__GetAppliedUserAuthorityListResponse *ns5__getAppliedUserAuthorityListResponse);
};
#endif
