#define ERROR                            1
#define OR                               2
#define XOR                              3
#define AND                              4
#define NOT                              5
#define NEAR                             6
#define ADJ                              7
#define LOVE                             8
#define HATE                             9
#define HATE_AFTER_AND                  10
#define SYNONYM                         11
#define TERM                            12
#define GROUP_TERM                      13
#define PHR_TERM                        14
#define EDIT_TERM                       15
#define WILD_TERM                       16
#define PARTIAL_TERM                    17
#define BOOLEAN_FILTER                  18
#define RANGE                           19
#define QUOTE                           20
#define BRA                             21
#define KET                             22
#define CJKTERM                         23
#define EMPTY_GROUP_OK                  24
