// PROTOBUF-INTERNAL.H
//
#ifndef PROTOBUF_INTERNAL_H
#define PROTOBUF_INTERNAL_H
#define WINDOWS_IGNORE_PACKING_MISMATCH // @v11.3.1
//#define SLIB_INCLUDE_CPPSTDLIBS
//#include <slib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <stdarg.h>
#include <float.h>
#include <ctype.h>
#include <locale.h>
#include <sys/types.h>
#include <assert.h>
#ifdef _WIN32
	#include <fcntl.h>
#else
	#include <unistd.h>
#endif

#include <algorithm>
#include <cstring>
#include <utility>
#include <atomic>
#include <sstream>
#include <vector>
#include <tuple>
#include <unordered_set>
#include <type_traits>
#include <cstdint>
#include <limits>
#include <iomanip>
#include <ostream>  // NOLINT(readability/streams)
#include <memory>
#include <string>
#include <climits>
#include <cstdio>
#include <cmath>
#include <iterator>
#include <ctime>
#include <stack>
#include <iostream>
#include <unordered_map>
#include <array>
#include <functional>
#include <map>
#include <set>
#include <cstddef>
#include <new>
#include <cctype>
#include <fstream>
#include <queue>
#include <typeinfo>
#include <cerrno>
#include <random>
#include <iosfwd>

#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/logging.h>
#include <google/protobuf/stubs/mutex.h>
#include <google/protobuf/stubs/strutil.h>
#include <google/protobuf/stubs/substitute.h>
#include <google/protobuf/stubs/stl_util.h>
#include <google/protobuf/stubs/casts.h>
#include <google/protobuf/stubs/hash.h>
#include <google/protobuf/stubs/map_util.h>
#include <google/protobuf/stubs/stringprintf.h>
#include <google/protobuf/stubs/bytestream.h>
#include <google/protobuf/stubs/status.h>
#include <google/protobuf/stubs/mathutil.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_lite.h>
#include <google/protobuf/map_type_handler.h>
#include <google/protobuf/message.h>
#include <google/protobuf/port.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/map_field.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/any.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/io/tokenizer.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena_impl.h>
#include <google/protobuf/compiler/code_generator.h>
#include <google/protobuf/compiler/cpp/cpp_enum.h>
#include <google/protobuf/compiler/cpp/cpp_helpers.h>
#include <google/protobuf/compiler/cpp/cpp_names.h>
#include <google/protobuf/compiler/parser.h>
#include <google/protobuf/wire_format.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/reflection.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_ptr_field.h>
#include <google/protobuf/explicitly_constructed.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/dynamic_message.h>
#include <google/protobuf/message.h>
#include <google/protobuf/util/internal/datapiece.h>
#include <google/protobuf/util/internal/utility.h>
#include <google/protobuf/stubs/callback.h>
#include <google/protobuf/stubs/int128.h>
#include <google/protobuf/util/field_comparator.h>
#include <google/protobuf/util/message_differencer.h>
#include <google/protobuf/io/zero_copy_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>

#include <google/protobuf/util/internal/proto_writer.h>
#include <google/protobuf/util/internal/field_mask_utility.h>
#include <google/protobuf/util/internal/object_location_tracker.h>
#include <google/protobuf/util/internal/constants.h>
#include <google/protobuf/stubs/statusor.h>

#endif // PROTOBUF_INTERNAL_H