/* soapClient.cpp
   Generated by gSOAP 2.8.4 from d:\Papyrus\Src\Tools\Uhttsoap\universe_htt.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.4 2012-04-15 15:59:48 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SelectObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__UhttObjSelectCriteria *ObjSelectCriteria, struct ns1__SelectObjectResponse &_param_1)
{	struct ns1__SelectObject soap_tmp_ns1__SelectObject;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__SelectObject.ObjSelectCriteria = ObjSelectCriteria;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__SelectObject(soap, &soap_tmp_ns1__SelectObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SelectObject(soap, &soap_tmp_ns1__SelectObject, "ns1:SelectObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SelectObject(soap, &soap_tmp_ns1__SelectObject, "ns1:SelectObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_1)
		return soap_closesock(soap);
	soap_default_ns1__SelectObjectResponse(soap, &_param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__SelectObjectResponse(soap, &_param_1, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCOREWorld(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCOREWorldResponse &_param_2)
{	struct ns1__Get_USCOREWorld soap_tmp_ns1__Get_USCOREWorld;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCOREWorld.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCOREWorld(soap, &soap_tmp_ns1__Get_USCOREWorld);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCOREWorld(soap, &soap_tmp_ns1__Get_USCOREWorld, "ns1:Get_World", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCOREWorld(soap, &soap_tmp_ns1__Get_USCOREWorld, "ns1:Get_World", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_2)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCOREWorldResponse(soap, &_param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCOREWorldResponse(soap, &_param_2, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCORECurrency(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCORECurrencyResponse &_param_3)
{	struct ns1__Get_USCORECurrency soap_tmp_ns1__Get_USCORECurrency;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCORECurrency.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCORECurrency(soap, &soap_tmp_ns1__Get_USCORECurrency);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCORECurrency(soap, &soap_tmp_ns1__Get_USCORECurrency, "ns1:Get_Currency", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCORECurrency(soap, &soap_tmp_ns1__Get_USCORECurrency, "ns1:Get_Currency", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_3)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCORECurrencyResponse(soap, &_param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCORECurrencyResponse(soap, &_param_3, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCOREPersonKind(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCOREPersonKindResponse &_param_4)
{	struct ns1__Get_USCOREPersonKind soap_tmp_ns1__Get_USCOREPersonKind;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCOREPersonKind.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCOREPersonKind(soap, &soap_tmp_ns1__Get_USCOREPersonKind);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCOREPersonKind(soap, &soap_tmp_ns1__Get_USCOREPersonKind, "ns1:Get_PersonKind", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCOREPersonKind(soap, &soap_tmp_ns1__Get_USCOREPersonKind, "ns1:Get_PersonKind", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_4)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCOREPersonKindResponse(soap, &_param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCOREPersonKindResponse(soap, &_param_4, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCOREPersonCategory(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCOREPersonCategoryResponse &_param_5)
{	struct ns1__Get_USCOREPersonCategory soap_tmp_ns1__Get_USCOREPersonCategory;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCOREPersonCategory.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCOREPersonCategory(soap, &soap_tmp_ns1__Get_USCOREPersonCategory);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCOREPersonCategory(soap, &soap_tmp_ns1__Get_USCOREPersonCategory, "ns1:Get_PersonCategory", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCOREPersonCategory(soap, &soap_tmp_ns1__Get_USCOREPersonCategory, "ns1:Get_PersonCategory", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_5)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCOREPersonCategoryResponse(soap, &_param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCOREPersonCategoryResponse(soap, &_param_5, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCORERegisterType(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCORERegisterTypeResponse &_param_6)
{	struct ns1__Get_USCORERegisterType soap_tmp_ns1__Get_USCORERegisterType;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCORERegisterType.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCORERegisterType(soap, &soap_tmp_ns1__Get_USCORERegisterType);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCORERegisterType(soap, &soap_tmp_ns1__Get_USCORERegisterType, "ns1:Get_RegisterType", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCORERegisterType(soap, &soap_tmp_ns1__Get_USCORERegisterType, "ns1:Get_RegisterType", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_6)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCORERegisterTypeResponse(soap, &_param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCORERegisterTypeResponse(soap, &_param_6, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCOREPerson(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCOREPersonResponse &_param_7)
{	struct ns1__Get_USCOREPerson soap_tmp_ns1__Get_USCOREPerson;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCOREPerson.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCOREPerson(soap, &soap_tmp_ns1__Get_USCOREPerson);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCOREPerson(soap, &soap_tmp_ns1__Get_USCOREPerson, "ns1:Get_Person", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCOREPerson(soap, &soap_tmp_ns1__Get_USCOREPerson, "ns1:Get_Person", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_7)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCOREPersonResponse(soap, &_param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCOREPersonResponse(soap, &_param_7, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCOREGoodsGroup(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCOREGoodsGroupResponse &_param_8)
{	struct ns1__Get_USCOREGoodsGroup soap_tmp_ns1__Get_USCOREGoodsGroup;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCOREGoodsGroup.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCOREGoodsGroup(soap, &soap_tmp_ns1__Get_USCOREGoodsGroup);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCOREGoodsGroup(soap, &soap_tmp_ns1__Get_USCOREGoodsGroup, "ns1:Get_GoodsGroup", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCOREGoodsGroup(soap, &soap_tmp_ns1__Get_USCOREGoodsGroup, "ns1:Get_GoodsGroup", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_8)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCOREGoodsGroupResponse(soap, &_param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCOREGoodsGroupResponse(soap, &_param_8, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCOREBrand(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCOREBrandResponse &_param_9)
{	struct ns1__Get_USCOREBrand soap_tmp_ns1__Get_USCOREBrand;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCOREBrand.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCOREBrand(soap, &soap_tmp_ns1__Get_USCOREBrand);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCOREBrand(soap, &soap_tmp_ns1__Get_USCOREBrand, "ns1:Get_Brand", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCOREBrand(soap, &soap_tmp_ns1__Get_USCOREBrand, "ns1:Get_Brand", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_9)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCOREBrandResponse(soap, &_param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCOREBrandResponse(soap, &_param_9, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCOREGoods(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCOREGoodsResponse &_param_10)
{	struct ns1__Get_USCOREGoods soap_tmp_ns1__Get_USCOREGoods;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCOREGoods.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCOREGoods(soap, &soap_tmp_ns1__Get_USCOREGoods);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCOREGoods(soap, &soap_tmp_ns1__Get_USCOREGoods, "ns1:Get_Goods", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCOREGoods(soap, &soap_tmp_ns1__Get_USCOREGoods, "ns1:Get_Goods", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_10)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCOREGoodsResponse(soap, &_param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCOREGoodsResponse(soap, &_param_10, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Get_USCORECalendar(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__Get_USCORECalendarResponse &_param_11)
{	struct ns1__Get_USCORECalendar soap_tmp_ns1__Get_USCORECalendar;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Get_USCORECalendar.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Get_USCORECalendar(soap, &soap_tmp_ns1__Get_USCORECalendar);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Get_USCORECalendar(soap, &soap_tmp_ns1__Get_USCORECalendar, "ns1:Get_Calendar", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Get_USCORECalendar(soap, &soap_tmp_ns1__Get_USCORECalendar, "ns1:Get_Calendar", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_11)
		return soap_closesock(soap);
	soap_default_ns1__Get_USCORECalendarResponse(soap, &_param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__Get_USCORECalendarResponse(soap, &_param_11, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SetGoodsCode(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__UhttArCode *ArCode, struct ns1__SetGoodsCodeResponse &_param_12)
{	struct ns1__SetGoodsCode soap_tmp_ns1__SetGoodsCode;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__SetGoodsCode.ArCode = ArCode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__SetGoodsCode(soap, &soap_tmp_ns1__SetGoodsCode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SetGoodsCode(soap, &soap_tmp_ns1__SetGoodsCode, "ns1:SetGoodsCode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SetGoodsCode(soap, &soap_tmp_ns1__SetGoodsCode, "ns1:SetGoodsCode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_12)
		return soap_closesock(soap);
	soap_default_ns1__SetGoodsCodeResponse(soap, &_param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__SetGoodsCodeResponse(soap, &_param_12, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GetGoodsCode(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__UhttArCode *ArCode, struct ns1__GetGoodsCodeResponse &_param_13)
{	struct ns1__GetGoodsCode soap_tmp_ns1__GetGoodsCode;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__GetGoodsCode.ArCode = ArCode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__GetGoodsCode(soap, &soap_tmp_ns1__GetGoodsCode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetGoodsCode(soap, &soap_tmp_ns1__GetGoodsCode, "ns1:GetGoodsCode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetGoodsCode(soap, &soap_tmp_ns1__GetGoodsCode, "ns1:GetGoodsCode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_13)
		return soap_closesock(soap);
	soap_default_ns1__GetGoodsCodeResponse(soap, &_param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__GetGoodsCodeResponse(soap, &_param_13, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__SetGoodsPrice(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__UhttQuot *Quot, struct ns1__SetGoodsPriceResponse &_param_14)
{	struct ns1__SetGoodsPrice soap_tmp_ns1__SetGoodsPrice;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__SetGoodsPrice.Quot = Quot;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__SetGoodsPrice(soap, &soap_tmp_ns1__SetGoodsPrice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SetGoodsPrice(soap, &soap_tmp_ns1__SetGoodsPrice, "ns1:SetGoodsPrice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SetGoodsPrice(soap, &soap_tmp_ns1__SetGoodsPrice, "ns1:SetGoodsPrice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_14)
		return soap_closesock(soap);
	soap_default_ns1__SetGoodsPriceResponse(soap, &_param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__SetGoodsPriceResponse(soap, &_param_14, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GetGoodsPrice(struct soap *soap, const char *soap_endpoint, const char *soap_action, ns1__UhttQuot *Quot, struct ns1__GetGoodsPriceResponse &_param_15)
{	struct ns1__GetGoodsPrice soap_tmp_ns1__GetGoodsPrice;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__GetGoodsPrice.Quot = Quot;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__GetGoodsPrice(soap, &soap_tmp_ns1__GetGoodsPrice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetGoodsPrice(soap, &soap_tmp_ns1__GetGoodsPrice, "ns1:GetGoodsPrice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetGoodsPrice(soap, &soap_tmp_ns1__GetGoodsPrice, "ns1:GetGoodsPrice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_15)
		return soap_closesock(soap);
	soap_default_ns1__GetGoodsPriceResponse(soap, &_param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__GetGoodsPriceResponse(soap, &_param_15, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__GetSpoiledSeries(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__GetSpoiledSeriesResponse &_param_16)
{	struct ns1__GetSpoiledSeries soap_tmp_ns1__GetSpoiledSeries;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__GetSpoiledSeries.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__GetSpoiledSeries(soap, &soap_tmp_ns1__GetSpoiledSeries);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetSpoiledSeries(soap, &soap_tmp_ns1__GetSpoiledSeries, "ns1:GetSpoiledSeries", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetSpoiledSeries(soap, &soap_tmp_ns1__GetSpoiledSeries, "ns1:GetSpoiledSeries", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_16)
		return soap_closesock(soap);
	soap_default_ns1__GetSpoiledSeriesResponse(soap, &_param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__GetSpoiledSeriesResponse(soap, &_param_16, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Login(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *Login, char *Password, struct ns1__LoginResponse &_param_17)
{	struct ns1__Login soap_tmp_ns1__Login;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Login.Login = Login;
	soap_tmp_ns1__Login.Password = Password;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Login(soap, &soap_tmp_ns1__Login);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Login(soap, &soap_tmp_ns1__Login, "ns1:Login", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Login(soap, &soap_tmp_ns1__Login, "ns1:Login", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_17)
		return soap_closesock(soap);
	soap_default_ns1__LoginResponse(soap, &_param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__LoginResponse(soap, &_param_17, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__Logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, int ID, struct ns1__LogoutResponse &_param_18)
{	struct ns1__Logout soap_tmp_ns1__Logout;
	if (!soap_endpoint)
		soap_endpoint = "http://localhost/Universe-HTT/soap/universe_htt.php";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__Logout.ID = ID;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns1__Logout(soap, &soap_tmp_ns1__Logout);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__Logout(soap, &soap_tmp_ns1__Logout, "ns1:Logout", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__Logout(soap, &soap_tmp_ns1__Logout, "ns1:Logout", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_param_18)
		return soap_closesock(soap);
	soap_default_ns1__LogoutResponse(soap, &_param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_get_ns1__LogoutResponse(soap, &_param_18, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
