butil -stat ACCOUNT.BTR
butil -stat ACCTREL.BTR
butil -stat ACCTURN.BTR
butil -stat ADVBITEM.BTR
butil -stat ARGCODE.BTR
butil -stat ARTICLE.BTR
butil -stat BALANCE.BTR
butil -stat BARCODE.BTR
butil -stat bill.BTR
butil -stat billamt.BTR
butil -stat BIZSCORE.BTR
butil -stat BIZSGLOB.BTR
butil -stat BNKACCT.BTR
butil -stat BUDGITEM.BTR
butil -stat CASHDCRD.BTR
butil -stat CCEXT.BTR
butil -stat ccheck.BTR
butil -stat CCLINE.BTR
butil -stat CCLNEXT.BTR
butil -stat CCPAYM.BTR
butil -stat CCURPRIC.BTR
butil -stat CGLINE.BTR
butil -stat CHKOPJ.BTR
butil -stat CITY.BTR
butil -stat COUNTRY.BTR
butil -stat CPTRFR.BTR
butil -stat CRATE.BTR
butil -stat CREDOPAY.BTR
butil -stat CSESS.BTR
butil -stat CURREST.BTR
butil -stat dls.BTR
butil -stat dlso.BTR
butil -stat EGAISPROD.BTR
butil -stat EGAISPSN.BTR
butil -stat EGAISREFA.BTR
butil -stat FIASADDR.BTR
butil -stat FIASHOUSE.BTR
butil -stat GDSDEBT.BTR
butil -stat GOODS2.BTR
butil -stat GOODSEXT.BTR
butil -stat GSTAT.BTR
butil -stat INVENTRY.BTR
butil -stat LCREST.BTR
butil -stat location.BTR
butil -stat LOCTRFR.BTR
butil -stat LOTXCODE.BTR
butil -stat MRPLINE.BTR
butil -stat MRPTAB.BTR
butil -stat OBJASSOC.BTR
butil -stat OBJLIKEN.BTR
butil -stat OBJSYNC.BTR
butil -stat OBJSYQUE.BTR
butil -stat OBJTAG.BTR
butil -stat OBJVER.BTR
butil -stat PACKAGE.BTR
butil -stat PAYPLAN.BTR
butil -stat PCKGLINK.BTR
butil -stat PERSKIND.BTR
butil -stat PERSON.BTR
butil -stat PLINE.BTR
butil -stat PLIST.BTR
butil -stat PRJTASK.BTR
butil -stat PROCESSR.BTR
butil -stat PROJECT.BTR
butil -stat prop.BTR
butil -stat PSALES.BTR
butil -stat PSNEVENT.BTR
butil -stat PSNPOST.BTR
butil -stat QCERT.BTR
butil -stat QUOT.BTR
butil -stat QUOT2.BTR
butil -stat QUOTREL.BTR
butil -stat receipt.BTR
butil -stat REF.BTR
butil -stat REF2.BTR
butil -stat REGION.BTR
butil -stat REGISTER.BTR
butil -stat SALARY.BTR
butil -stat SALE.BTR
butil -stat SCARD.BTR
butil -stat SCARDOP.BTR
butil -stat sj.BTR
butil -stat SJR.BTR
butil -stat SPCSN.BTR
butil -stat SPCSN2.BTR
butil -stat STAFCAL.BTR
butil -stat STAFFL.BTR
butil -stat TECH.BTR
butil -stat TEXTREF.BTR
butil -stat transfer.BTR
butil -stat TSESS.BTR
butil -stat TSESSLN.BTR
butil -stat UFP.BTR
butil -stat UFPSESS.BTR
butil -stat UNXTXREF.BTR
butil -stat UUIDREF.BTR
butil -stat VATBOOK.BTR
butil -stat VETISDOC.BTR
butil -stat VETISENT.BTR
butil -stat VETISPRD.BTR
butil -stat VETISPSN.BTR
butil -stat WORKBOOK.BTR
butil -stat WORLD.BTR
butil -stat XBILL.BTR
butil -stat xgoods.BTR
butil -stat XTRFR.BTR
butil -stat ZREPORT.BTR
